import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { FormModal } from '../components/FormModal'
import { useAuth } from '../hooks/useAuth'
import { ApiError } from '../services/apiClient'
import { checkCrossReference, createCrossReference, deleteCrossReference, getCrossReference, listCrossReferences, searchCrossReferenceParts, updateCrossReference } from '../services/crossReferencesApi'
import type { CrossRefConflict, CrossReference, CrossReferencePayload, CrossReferenceStatus, RelationType } from '../types/crossReferences'
import type { Part } from '../types/parts'

const relationCopy: Record<RelationType,string> = { OEM:'OEM', aftermarket:'售后件', replacement:'替代', compatible:'兼容', equivalent:'等同', supersedes:'升级替代' }
const statusCopy: Record<CrossReferenceStatus,string> = { pending:'待审核', active:'有效', inactive:'停用', rejected:'拒绝' }
const blank: CrossReferencePayload = { source_part_id:'', target_part_id:'', relation_type:'replacement', reliability:.75, restrictions:null, brand:null, priority:0, source:null, notes:null, status:'active' }
const payloadOf = (item: CrossReference): CrossReferencePayload => ({ source_part_id:item.source_part_id,target_part_id:item.target_part_id,relation_type:item.relation_type,reliability:Number(item.reliability),restrictions:item.restrictions,brand:item.brand,priority:item.priority,source:item.source,notes:item.notes,status:item.status })

function PartPicker({ name, label, selectedId, selectedLabel, onSelect }: { name:string;label:string;selectedId:string;selectedLabel:string;onSelect:(id:string)=>void }) {
  const [term,setTerm] = useState(selectedLabel); const [options,setOptions] = useState<Part[]>([]); const [loading,setLoading] = useState(false)
  useEffect(() => { if (term.trim().length < 2) return; const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); void searchCrossReferenceParts(term.trim(),controller.signal).then(page => setOptions(page.items)).catch(reason => { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setOptions([]) }).finally(() => setLoading(false)) },250); return () => { window.clearTimeout(timer); controller.abort() } },[term])
  const merged = selectedId && !options.some(item => item.id === selectedId) ? [{ id:selectedId,part_no:selectedLabel,brand:'',name_zh:selectedLabel,is_active:true } as Part,...options] : options
  return <label className="field-wide part-selector">{label}<span><input aria-label={`${label}搜索`} value={term} onChange={event => setTerm(event.target.value)} placeholder="输入编号、品牌或名称（至少 2 字符）" /><select aria-label={label} name={name} required value={selectedId} onChange={event => onSelect(event.target.value)}><option value="">{loading ? '正在检索…' : '选择配件'}</option>{merged.map(item => <option key={item.id} value={item.id}>{item.part_no} · {item.brand} · {item.name_zh}</option>)}</select></span></label>
}

function ConflictPanel({ conflicts, onAction }: { conflicts:CrossRefConflict[];onAction:(item:CrossRefConflict)=>void }) {
  if (!conflicts.length) return <p className="conflict-clear field-wide"><b>✓ 路径检查通过</b> 未发现重复或循环关系</p>
  return <section className="conflict-panel field-wide" aria-live="polite"><header><b>关系冲突 · {conflicts.length}</b><span>保存已阻止</span></header>{conflicts.map((item,index) => <article key={`${item.type}-${index}`}><div><strong>{item.message}</strong>{item.path && <small>{item.path.map(node => node.part_no).join(' → ')}</small>}</div><button type="button" onClick={() => onAction(item)}>{item.action.label}</button></article>)}</section>
}

function CrossRefForm({ value, sourceLabel, targetLabel, conflicts, onPairChange, onConflictAction, error }: { value:CrossReferencePayload;sourceLabel:string;targetLabel:string;conflicts:CrossRefConflict[];onPairChange:(field:'source_part_id'|'target_part_id',id:string)=>void;onConflictAction:(item:CrossRefConflict)=>void;error:string }) {
  return <><PartPicker name="source_part_id" label="原件 / SOURCE" selectedId={value.source_part_id} selectedLabel={sourceLabel} onSelect={id => onPairChange('source_part_id',id)} /><div className="relation-arrow field-wide"><span>SOURCE</span><i>→</i><span>REPLACEMENT</span></div><PartPicker name="target_part_id" label="替代件 / TARGET" selectedId={value.target_part_id} selectedLabel={targetLabel} onSelect={id => onPairChange('target_part_id',id)} /><label>关系类型<select name="relation_type" defaultValue={value.relation_type}>{Object.entries(relationCopy).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>可靠度<select name="reliability" defaultValue={String(value.reliability)}><option value=".95">高 / HIGH</option><option value=".75">中 / MEDIUM</option><option value=".5">低 / LOW</option></select></label><label>关系品牌<input name="brand" defaultValue={value.brand || ''} /></label><label>优先级<input name="priority" type="number" min="0" max="10000" defaultValue={value.priority} /></label><label>来源<input name="source" defaultValue={value.source || ''} placeholder="供应商 / OEM 公告" /></label><label>状态<select name="status" defaultValue={value.status}>{Object.entries(statusCopy).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="field-wide">适配限制<textarea name="restrictions" rows={3} defaultValue={value.restrictions || ''} /></label><label className="field-wide">备注<textarea name="notes" rows={3} defaultValue={value.notes || ''} /></label>{value.source_part_id && value.target_part_id && <ConflictPanel conflicts={conflicts} onAction={onConflictAction} />}{error && <p className="form-error field-wide" role="alert">{error}</p>}</>
}

function parsePayload(form:HTMLFormElement):CrossReferencePayload { const data=new FormData(form); const nullable=(key:string)=>String(data.get(key)||'').trim()||null; return { source_part_id:String(data.get('source_part_id')),target_part_id:String(data.get('target_part_id')),relation_type:String(data.get('relation_type')) as RelationType,reliability:Number(data.get('reliability')),brand:nullable('brand'),priority:Number(data.get('priority')||0),source:nullable('source'),restrictions:nullable('restrictions'),notes:nullable('notes'),status:String(data.get('status')) as CrossReferenceStatus } }

export function CrossReferencesPage() {
  const { user }=useAuth(); const writable=user?.role==='admin'; const [params,setParams]=useSearchParams(); const [rows,setRows]=useState<CrossReference[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [draft,setDraft]=useState(params.get('q')||''); const [editor,setEditor]=useState<CrossReference|'new'|null>(null); const [pair,setPair]=useState(blank); const [conflicts,setConflicts]=useState<CrossRefConflict[]>([]); const [formError,setFormError]=useState(''); const [busy,setBusy]=useState(false); const [deleteTarget,setDeleteTarget]=useState<CrossReference|null>(null)
  const page=Math.max(1,Number(params.get('page')||1)); const pageSize=20; const pages=Math.max(1,Math.ceil(total/pageSize))
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const data=await listCrossReferences({q:params.get('q')||undefined,relation_type:params.get('relation_type')||undefined,status:params.get('status')||undefined,part_id:params.get('part_id')||undefined,direction:params.get('direction')||'all',sort_by:params.get('sort')||'priority',sort_dir:params.get('dir')||'desc',page,page_size:pageSize},signal);setRows(data.items);setTotal(data.total)}catch(reason){if(!(reason instanceof DOMException&&reason.name==='AbortError'))setError(reason instanceof Error?reason.message:'读取失败')}finally{if(!signal?.aborted)setLoading(false)}},[page,params])
  useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal));return()=>controller.abort()},[load])
  useEffect(()=>{if(!pair.source_part_id||!pair.target_part_id)return;const timer=window.setTimeout(()=>void checkCrossReference(pair.source_part_id,pair.target_part_id,editor!=='new'&&editor?editor.id:undefined).then(result=>setConflicts(result.conflicts)).catch(()=>undefined),200);return()=>window.clearTimeout(timer)},[editor,pair.source_part_id,pair.target_part_id])
  const patchParams=(values:Record<string,string>)=>{const next=new URLSearchParams(params);Object.entries(values).forEach(([key,value])=>value?next.set(key,value):next.delete(key));if(!('page'in values))next.set('page','1');setParams(next)}
  const openEditor=(item:CrossReference|'new')=>{setEditor(item);setPair(item==='new'?blank:payloadOf(item));setConflicts([]);setFormError('')}
  const conflictAction=async(item:CrossRefConflict)=>{if(item.action.kind==='edit_existing'&&item.action.relation_id){setBusy(true);try{openEditor(await getCrossReference(item.action.relation_id))}finally{setBusy(false)}}else{setPair(current=>({...current,target_part_id:''}));setConflicts([])}}
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editor||busy)return;setBusy(true);setFormError('');try{const payload=parsePayload(event.currentTarget);const report=await checkCrossReference(payload.source_part_id,payload.target_part_id,editor!=='new'?editor.id:undefined);if(!report.can_save){setConflicts(report.conflicts);setFormError('请先处理关系冲突');return}if(editor==='new')await createCrossReference(payload);else await updateCrossReference(editor.id,payload);setEditor(null);await load()}catch(reason){if(reason instanceof ApiError){const data=reason.data as {conflicts?:CrossRefConflict[]}|undefined;if(data?.conflicts)setConflicts(data.conflicts)}setFormError(reason instanceof Error?reason.message:'保存失败')}finally{setBusy(false)}}
  const remove=async()=>{if(!deleteTarget||busy)return;setBusy(true);try{await deleteCrossReference(deleteTarget.id);setDeleteTarget(null);await load()}finally{setBusy(false)}}
  return <div className="crossrefs-page"><header className="page-heading"><div><p className="eyebrow">CROSS REFERENCE / DIRECTED GRAPH</p><h1>替代件管理</h1><p>以有向关系维护原件、替代件与可信证据；冲突在入库前完成拦截。</p></div><span>ACCESS <b>{writable?'ADMIN WRITE':'OPERATOR READ ONLY'}</b></span></header>
    {params.get('part_id')&&<p className="perspective-banner">配件视角已启用 · {params.get('direction')==='source'?'作为原件':params.get('direction')==='target'?'作为替代件':'全部方向'} <button onClick={()=>patchParams({part_id:'',direction:''})}>退出视角</button></p>}
    <section className="crossref-filters"><form onSubmit={event=>{event.preventDefault();patchParams({q:draft})}}><label>编号 / 品牌搜索<input aria-label="搜索替代关系" value={draft} onChange={event=>setDraft(event.target.value)} /></label><label>关系<select value={params.get('relation_type')||''} onChange={event=>patchParams({relation_type:event.target.value})}><option value="">全部</option>{Object.entries(relationCopy).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>状态<select value={params.get('status')||''} onChange={event=>patchParams({status:event.target.value})}><option value="">全部</option>{Object.entries(statusCopy).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>方向<select value={params.get('direction')||'all'} onChange={event=>patchParams({direction:event.target.value})}><option value="all">双向</option><option value="source">作为原件</option><option value="target">作为替代件</option></select></label><button className="button">查询</button></form></section>
    <section className="crossref-command"><div><b>{total}</b><span>条关系 · PRIORITY DESC</span></div>{writable&&<button className="button" onClick={()=>openEditor('new')}>新增关系</button>}</section>
    <section className="crossref-deck" aria-busy={loading}>{loading?<div className="table-state"><i/>正在读取关系图…</div>:error?<div className="table-state table-state--error"><b>读取失败</b><span>{error}</span><button onClick={()=>void load()}>重试</button></div>:!rows.length?<div className="table-state"><b>没有符合条件的关系</b><span>调整筛选或建立第一条有向关系。</span></div>:<div className="table-scroll"><table><caption className="sr-only">替代件关系列表</caption><thead><tr><th>原件 / SOURCE</th><th>方向</th><th>替代件 / TARGET</th><th>关系</th><th>质量 / 优先级</th><th>来源</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.source_part.part_no}</strong><small>{row.source_part.brand}</small></td><td><span className="flow-arrow">→</span></td><td><strong>{row.target_part.part_no}</strong><small>{row.target_part.brand}</small></td><td><b>{relationCopy[row.relation_type]}</b><small>{row.brand||'跨品牌'}</small></td><td><span className={`quality quality--${row.quality}`}>{row.quality.toUpperCase()} · {Math.round(Number(row.reliability)*100)}%</span><small>P{row.priority}</small></td><td>{row.source||'—'}</td><td><span className={`record-state record-state--${row.status}`}>{statusCopy[row.status]}</span></td><td><div className="row-actions"><Link to={`/parts/${row.source_part_id}`}>原件</Link><Link to={`/parts/${row.target_part_id}`}>替代件</Link>{writable&&<><button onClick={()=>openEditor(row)}>编辑</button><button onClick={()=>setDeleteTarget(row)}>删除</button></>}</div></td></tr>)}</tbody></table></div>}<nav className="pagination"><button disabled={page<=1} onClick={()=>patchParams({page:String(page-1)})}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page>=pages} onClick={()=>patchParams({page:String(page+1)})}>下一页</button></nav></section>
    <FormModal open={editor!=null} title={editor==='new'?'新增替代关系':`编辑 ${editor?.source_part_no||''} → ${editor?.target_part_no||''}`} busy={busy} disabled={conflicts.length>0} onClose={()=>setEditor(null)} onSubmit={save}><CrossRefForm key={editor==='new'?'new':editor?.id} value={pair} sourceLabel={editor==='new'?'':editor?.source_part_no||''} targetLabel={editor==='new'?'':editor?.target_part_no||''} conflicts={conflicts} onPairChange={(field,id)=>{setConflicts([]);setPair(current=>({...current,[field]:id}))}} onConflictAction={item=>void conflictAction(item)} error={formError}/></FormModal>
    <ConfirmDialog open={deleteTarget!=null} title="删除替代关系" description={`${deleteTarget?.source_part_no||''} → ${deleteTarget?.target_part_no||''} 将被永久删除。`} busy={busy} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>void remove()}/>
  </div>
}
