import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { AuthContext, type AuthContextValue } from '../contexts/AuthContext'
import * as crossRefApi from '../services/crossReferencesApi'
import type { CrossReference } from '../types/crossReferences'
import type { Part } from '../types/parts'
import { CrossReferencesPage } from './CrossReferencesPage'

vi.mock('../services/crossReferencesApi')
beforeAll(()=>{HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}})
const source={id:'part-a',sku:'A',part_no:'PN-A',oem_no:null,alternate_no:null,brand:'CAT',category:null,name_zh:'原滤芯',name_en:null,name_vi:null,specs:{},unit:'件',price:null,stock:1,stock_status:'in_stock',is_active:true,notes:null,images:[],created_at:'2026',updated_at:'2026'} as Part
const target={...source,id:'part-b',sku:'B',part_no:'PN-B',brand:'Donaldson',name_zh:'替代滤芯'}
const row={id:'ref-1',source_part_id:'part-a',target_part_id:'part-b',source_part_no:'PN-A',target_part_no:'PN-B',source_part:{id:'part-a',part_no:'PN-A',brand:'CAT',name:'原滤芯',is_active:true},target_part:{id:'part-b',part_no:'PN-B',brand:'Donaldson',name:'替代滤芯',is_active:true},direction:'source_to_target',quality:'high',relation_type:'replacement',reliability:.95,restrictions:null,brand:'Donaldson',priority:20,source:'OEM bulletin',notes:null,status:'active',created_at:'2026',updated_at:'2026'} as CrossReference
const auth=(role:'admin'|'operator'):AuthContextValue=>({user:{id:'u',username:role,role},ready:true,signIn:vi.fn(),signOut:vi.fn()})
const renderPage=(entry='/cross-refs',role:'admin'|'operator'='admin')=>render(<AuthContext.Provider value={auth(role)}><MemoryRouter initialEntries={[entry]}><Routes><Route path="/cross-refs" element={<CrossReferencesPage/>}/><Route path="/parts/:partId" element={<p>PART DETAIL</p>}/></Routes></MemoryRouter></AuthContext.Provider>)

describe('CrossReferencesPage',()=>{
  beforeEach(()=>{vi.clearAllMocks();vi.mocked(crossRefApi.listCrossReferences).mockResolvedValue({items:[structuredClone(row)],total:41,page:2,page_size:20});vi.mocked(crossRefApi.searchCrossReferenceParts).mockResolvedValue({items:[source,target],total:2,page:1,page_size:20});vi.mocked(crossRefApi.checkCrossReference).mockResolvedValue({can_save:true,conflicts:[]});vi.mocked(crossRefApi.createCrossReference).mockResolvedValue(row);vi.mocked(crossRefApi.getCrossReference).mockResolvedValue(row)})
  it('uses URL-backed search, filters, direction and pagination while showing directed evidence',async()=>{renderPage('/cross-refs?q=PN&relation_type=replacement&status=active&part_id=part-a&direction=source&page=2');expect(await screen.findByText('PN-A')).toBeInTheDocument();expect(crossRefApi.listCrossReferences).toHaveBeenCalledWith(expect.objectContaining({q:'PN',relation_type:'replacement',status:'active',part_id:'part-a',direction:'source',page:2}),expect.any(AbortSignal));expect(screen.getByText('OEM bulletin')).toBeInTheDocument();expect(screen.getByText('HIGH · 95%')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('搜索替代关系'),{target:{value:'Donaldson'}});fireEvent.submit(screen.getByLabelText('搜索替代关系').closest('form')!);await waitFor(()=>expect(crossRefApi.listCrossReferences).toHaveBeenLastCalledWith(expect.objectContaining({q:'Donaldson',page:1}),expect.any(AbortSignal)))})
  it('checks a selected pair and renders an actionable cycle path',async()=>{vi.mocked(crossRefApi.checkCrossReference).mockResolvedValue({can_save:false,conflicts:[{type:'cycle',message:'该关系会形成循环引用',path:[{id:'part-a',part_no:'PN-A'},{id:'part-b',part_no:'PN-B'},{id:'part-a',part_no:'PN-A'}],action:{kind:'change_target',label:'更换替代件'}}]});renderPage();await screen.findByText('PN-A');fireEvent.click(screen.getByRole('button',{name:'新增关系'}));const dialog=screen.getByRole('dialog',{name:'新增替代关系'});fireEvent.change(within(dialog).getByLabelText('原件 / SOURCE搜索'),{target:{value:'PN'}});fireEvent.change(within(dialog).getByLabelText('替代件 / TARGET搜索'),{target:{value:'PN'}});await within(dialog).findAllByRole('option',{name:/PN-A/});fireEvent.change(within(dialog).getByLabelText('原件 / SOURCE',{selector:'select'}),{target:{value:'part-a'}});fireEvent.change(within(dialog).getByLabelText('替代件 / TARGET',{selector:'select'}),{target:{value:'part-b'}});expect(await within(dialog).findByText('该关系会形成循环引用')).toBeInTheDocument();expect(within(dialog).getByText('PN-A → PN-B → PN-A')).toBeInTheDocument();expect(within(dialog).getByRole('button',{name:'保存记录'})).toBeDisabled();fireEvent.click(within(dialog).getByRole('button',{name:'更换替代件'}));expect(within(dialog).getByLabelText('替代件 / TARGET',{selector:'select'})).toHaveValue('')})
  it('keeps operator relation browsing and part navigation read only',async()=>{renderPage('/cross-refs','operator');expect(await screen.findByText('PN-A')).toBeInTheDocument();expect(screen.getByText(/OPERATOR READ ONLY/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'新增关系'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'编辑'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'原件'})).toHaveAttribute('href','/parts/part-a')})
})
