import { useState, type FormEvent } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'

export function LoginPage() {
  const { user, ready, signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  if (ready && user) return <Navigate to={user.role === 'operator' ? '/tickets' : '/'} replace />
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { await signIn(String(data.get('username') ?? '').trim(), String(data.get('password') ?? '')); const requested = (location.state as { from?: string } | null)?.from; navigate(requested?.startsWith('/') && !requested.startsWith('//') ? requested : '/', { replace: true }) } catch (reason) { setError(reason instanceof Error ? reason.message : '登录失败') } finally { setBusy(false) } }
  return <main className="login-screen"><section className="login-manifest"><div className="console-brand console-brand--large"><span className="console-mark">PM</span><div><b>PARTS·MATCH</b><small>OPERATIONS CONTROL</small></div></div><div className="manifest-copy"><p>AUTHORIZED PERSONNEL / 仅限授权人员</p><h1>配件匹配<br />运营控制台</h1><dl><div><dt>CATALOG</dt><dd>结构化配件目录</dd></div><div><dt>FITMENT</dt><dd>设备适配关系</dd></div><div><dt>TICKETS</dt><dd>人工核对队列</dd></div></dl></div><div className="login-bus" aria-hidden="true">BUS 01 ━━━━━ AUTH GATE ━━━━━ SECURE</div></section><section className="login-panel"><form onSubmit={event => void submit(event)}><p className="eyebrow">SESSION / 登录</p><h2>验证管理身份</h2><p>使用后台管理员或工单操作员账号。</p>{new URLSearchParams(location.search).get('password') === 'changed' && <div className="login-success" role="status">密码已修改，请使用新密码重新登录。</div>}<label>用户名<input name="username" autoComplete="username" required maxLength={100} autoFocus /></label><label>密码<input name="password" type="password" autoComplete="current-password" required minLength={8} maxLength={200} /></label>{error && <div className="login-error" role="alert">{error}</div>}<button className="button" type="submit" disabled={busy}>{busy ? '正在验证…' : '进入控制台'}</button><small>会话采用短期访问令牌与 HttpOnly 刷新凭证。</small></form></section></main>
}
