import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { FormModal } from '../components/FormModal'
import { useAuth } from '../hooks/useAuth'
import { listParts } from '../services/partsApi'
import { createFitment, createMachine, createMachineType, deleteFitment, deleteMachine, deleteMachineType, getMachine, getMachineOptions, importFitments, listFitments, listMachines, listMachineTypes, updateMachine, updateMachineType } from '../services/machinesApi'
import type { Fitment, Machine, MachinePayload, MachineType, CsvImportReport } from '../types/machines'
import type { Part } from '../types/parts'

const blankMachine: MachinePayload = { machine_type: '', brand: '', model: '', series: null, year: null, region: null, engine_model: null, notes: null }
const clean = (value: FormDataEntryValue | null) => String(value || '').trim() || null
const machinePayload = (form: HTMLFormElement): MachinePayload => { const data = new FormData(form); const year = clean(data.get('year')); return { machine_type: String(clean(data.get('machine_type')) || ''), brand: String(clean(data.get('brand')) || ''), model: String(clean(data.get('model')) || ''), series: clean(data.get('series')), year: year ? Number(year) : null, region: clean(data.get('region')), engine_model: clean(data.get('engine_model')), notes: clean(data.get('notes')) } }
const message = (reason: unknown, fallback: string) => reason instanceof Error ? reason.message : fallback

function MachineForm({ value, types, error }: { value: MachinePayload; types: MachineType[]; error: string }) {
  return <><label>设备类型<select name="machine_type" required defaultValue={value.machine_type}><option value="">请选择数据库类型</option>{types.filter(item => item.is_active || item.code === value.machine_type).map(item => <option value={item.code} key={item.id}>{item.name} · {item.code}</option>)}</select></label><label>品牌<input name="brand" required defaultValue={value.brand} /></label><label>型号<input name="model" required defaultValue={value.model} /></label><label>系列<input name="series" defaultValue={value.series || ''} /></label><label>年份<input name="year" type="number" min="1900" max="2200" defaultValue={value.year ?? ''} /></label><label>地区版本<input name="region" defaultValue={value.region || ''} /></label><label>发动机型号<input name="engine_model" defaultValue={value.engine_model || ''} /></label><label className="field-wide">备注<textarea name="notes" rows={3} defaultValue={value.notes || ''} /></label>{error && <p className="form-error field-wide" role="alert">{error}</p>}</>
}

export function MachinesPage() {
  const { user } = useAuth(); const writable = user?.role === 'admin'; const navigate = useNavigate(); const { machineId } = useParams(); const [params,setParams] = useSearchParams()
  const page = Math.max(1, Number(params.get('page')) || 1); const pageSize = 20
  const [rows,setRows] = useState<Machine[]>([]); const [total,setTotal] = useState(0); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [notice,setNotice] = useState('')
  const [options,setOptions] = useState<{brands:string[];types:MachineType[]}>({ brands:[], types:[] }); const [draft,setDraft] = useState(params.get('q') || '')
  const [editor,setEditor] = useState<Machine|'new'|null>(null); const [formBusy,setFormBusy] = useState(false); const [formError,setFormError] = useState(''); const [deleteTarget,setDeleteTarget] = useState<Machine|null>(null)
  const [typesOpen,setTypesOpen] = useState(false); const [allTypes,setAllTypes] = useState<MachineType[]>([]); const [typeEditor,setTypeEditor] = useState<MachineType|'new'|null>(null); const [deleteType,setDeleteType] = useState<MachineType|null>(null)
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); try { const data = await listMachines({ q: params.get('q') || undefined, brand: params.get('brand') || undefined, machine_type: params.get('type') || undefined, page, page_size: pageSize }, signal); setRows(data.items); setTotal(data.total) } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(message(reason,'设备列表读取失败')) } finally { if (!signal?.aborted) setLoading(false) } }, [page,params])
  const refreshOptions = useCallback(async () => { const [next,types] = await Promise.all([getMachineOptions(),listMachineTypes()]); setOptions(next); setAllTypes(types) }, [])
  useEffect(() => { const controller = new AbortController(); void Promise.resolve().then(() => load(controller.signal)); return () => controller.abort() }, [load])
  useEffect(() => { void Promise.resolve().then(refreshOptions).catch(() => undefined) }, [refreshOptions])
  const patchParams = (values: Record<string,string>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key,value]) => { if (value) next.set(key,value); else next.delete(key) }); if (!('page' in values)) next.set('page','1'); setParams(next) }
  const saveMachine = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editor || formBusy) return; setFormBusy(true); setFormError(''); try { const payload = machinePayload(event.currentTarget); if (editor === 'new') await createMachine(payload); else await updateMachine(editor.id,payload); setEditor(null); setNotice(editor === 'new' ? '设备已创建' : '设备已更新'); await Promise.all([load(),refreshOptions()]) } catch (reason) { setFormError(message(reason,'设备保存失败')) } finally { setFormBusy(false) } }
  const removeMachine = async () => { if (!deleteTarget || formBusy) return; setFormBusy(true); try { await deleteMachine(deleteTarget.id); if (machineId === deleteTarget.id) navigate(`/machines?${params}`); setDeleteTarget(null); setNotice('设备及其适配关系已删除'); await load() } catch (reason) { setError(message(reason,'设备删除失败')) } finally { setFormBusy(false) } }
  const saveType = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!typeEditor || formBusy) return; setFormBusy(true); setFormError(''); const data = new FormData(event.currentTarget); const payload = { code:String(data.get('code')||'').trim(), name:String(data.get('name')||'').trim(), sort_order:Number(data.get('sort_order')||0), is_active:String(data.get('is_active')) === 'true' }; try { if (typeEditor === 'new') await createMachineType(payload); else await updateMachineType(typeEditor.id,payload); setTypeEditor(null); setNotice('设备类型已保存'); await refreshOptions() } catch (reason) { setFormError(message(reason,'设备类型保存失败')) } finally { setFormBusy(false) } }
  const removeType = async () => { if (!deleteType || formBusy) return; setFormBusy(true); try { await deleteMachineType(deleteType.id); setDeleteType(null); setNotice('设备类型已删除'); await refreshOptions() } catch (reason) { setFormError(message(reason,'已被设备使用的类型不能删除')); setDeleteType(null) } finally { setFormBusy(false) } }
  const pages = Math.max(1,Math.ceil(total/pageSize)); const current = editor === 'new' ? blankMachine : editor ? { machine_type:editor.machine_type,brand:editor.brand,model:editor.model,series:editor.series,year:editor.year,region:editor.region,engine_model:editor.engine_model,notes:editor.notes } : blankMachine
  return <div className="machines-page"><header className="page-heading"><div><p className="eyebrow">MACHINE / MASTER REGISTER</p><h1>设备管理</h1><p>维护整机档案，并在同一设备详情中校准配件适配范围。</p></div><span>ACCESS <b>{writable ? 'ADMIN WRITE' : 'OPERATOR READ ONLY'}</b></span></header>
    <section className="machine-filter-deck"><form onSubmit={event => { event.preventDefault(); patchParams({q:draft}) }}><label>型号搜索<input aria-label="搜索设备型号" value={draft} onChange={event => setDraft(event.target.value)} placeholder="输入型号关键词" /></label><label>设备类型<select aria-label="设备类型筛选" value={params.get('type')||''} onChange={event => patchParams({type:event.target.value})}><option value="">全部类型</option>{options.types.map(item => <option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label>品牌<select aria-label="设备品牌筛选" value={params.get('brand')||''} onChange={event => patchParams({brand:event.target.value})}><option value="">全部品牌</option>{options.brands.map(item => <option key={item}>{item}</option>)}</select></label><button className="button" type="submit">查询</button></form></section>
    <section className="machine-command-bar"><div><b>{total}</b><span>台设备主档 · 类型来自数据库配置</span></div>{writable && <div><button className="button button--quiet" onClick={() => setTypesOpen(value => !value)}>管理设备类型</button><button className="button" onClick={() => { setFormError(''); setEditor('new') }}>新增设备</button></div>}</section>
    {notice && <p className="operation-notice" role="status">{notice}<button aria-label="关闭通知" onClick={() => setNotice('')}>×</button></p>}
    {typesOpen && <section className="machine-type-manager" aria-label="设备类型配置"><div className="section-title"><div><p className="eyebrow">DATABASE OPTIONS</p><h2>设备类型配置</h2></div><button className="button button--quiet" onClick={() => { setFormError(''); setTypeEditor('new') }}>新增类型</button></div>{formError && <p className="panel-error" role="alert">{formError}</p>}<div>{allTypes.map(item => <article key={item.id}><code>{item.code}</code><strong>{item.name}</strong><span>{item.is_active ? '启用' : '停用'} · 顺序 {item.sort_order}</span><button onClick={() => { setFormError(''); setTypeEditor(item) }}>编辑</button><button onClick={() => setDeleteType(item)}>删除</button></article>)}</div></section>}
    <section className="machines-deck" aria-busy={loading}>{loading ? <div className="table-state"><i />正在读取设备主档…</div> : error ? <div className="table-state table-state--error" role="alert"><b>读取失败</b><span>{error}</span><button onClick={() => void load()}>重试</button></div> : !rows.length ? <div className="table-state"><b>没有符合条件的设备</b><span>调整型号、类型或品牌筛选。</span></div> : <div className="table-scroll"><table><caption className="sr-only">设备列表</caption><thead><tr><th>设备类型</th><th>品牌</th><th>型号</th><th>系列</th><th>年份</th><th>地区</th><th>发动机型号</th><th>操作</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><span className="machine-type-chip">{options.types.find(item => item.code === row.machine_type)?.name || row.machine_type}</span></td><td>{row.brand}</td><td><strong>{row.model}</strong></td><td>{row.series||'—'}</td><td>{row.year||'—'}</td><td>{row.region||'—'}</td><td><code>{row.engine_model||'—'}</code></td><td><div className="row-actions"><Link to={`/machines/${row.id}?${params}`}>适配配件</Link>{writable && <><button onClick={() => { setFormError(''); setEditor(row) }}>编辑</button><button onClick={() => setDeleteTarget(row)}>删除</button></>}</div></td></tr>)}</tbody></table></div>}{!loading && !error && <nav className="pagination" aria-label="设备列表分页"><button disabled={page<=1} onClick={() => patchParams({page:String(page-1)})}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page>=pages} onClick={() => patchParams({page:String(page+1)})}>下一页</button></nav>}</section>
    <FormModal open={editor!=null} title={editor==='new'?'新增设备':`编辑 ${editor?.brand} ${editor?.model}`} busy={formBusy} onClose={() => setEditor(null)} onSubmit={saveMachine}><MachineForm key={editor==='new'?'new':editor?.id} value={current} types={allTypes} error={formError} /></FormModal>
    <FormModal open={typeEditor!=null} title={typeEditor==='new'?'新增设备类型':'编辑设备类型'} busy={formBusy} onClose={() => setTypeEditor(null)} onSubmit={saveType}><label>类型代码<input name="code" required pattern="[a-z0-9]+(?:[-_][a-z0-9]+)*" defaultValue={typeEditor==='new'?'':typeEditor?.code} /></label><label>显示名称<input name="name" required defaultValue={typeEditor==='new'?'':typeEditor?.name} /></label><label>排序<input name="sort_order" type="number" min="0" defaultValue={typeEditor==='new'?0:typeEditor?.sort_order} /></label><label>状态<select name="is_active" defaultValue={typeEditor==='new'?'true':String(typeEditor?.is_active)}><option value="true">启用</option><option value="false">停用</option></select></label>{formError && <p className="form-error field-wide" role="alert">{formError}</p>}</FormModal>
    <ConfirmDialog open={deleteTarget!=null} title="删除设备" description={`将永久删除 ${deleteTarget?.brand||''} ${deleteTarget?.model||''} 及其适配关系。`} busy={formBusy} onCancel={() => setDeleteTarget(null)} onConfirm={() => void removeMachine()} />
    <ConfirmDialog open={deleteType!=null} title="删除设备类型" description={`删除类型“${deleteType?.name||''}”；如有设备正在使用，后端会拒绝。`} busy={formBusy} onCancel={() => setDeleteType(null)} onConfirm={() => void removeType()} />
    {machineId && <MachineDetail machineId={machineId} writable={writable} onClose={() => navigate(`/machines?${params}`)} />}
  </div>
}

function MachineDetail({ machineId,writable,onClose }: {machineId:string;writable:boolean;onClose:()=>void}) {
  const [machine,setMachine] = useState<Machine|null>(null); const [fitments,setFitments] = useState<Fitment[]>([]); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [busy,setBusy] = useState(false)
  const [adding,setAdding] = useState(false); const [partQuery,setPartQuery] = useState(''); const [parts,setParts] = useState<Part[]>([]); const [deleteTarget,setDeleteTarget] = useState<Fitment|null>(null)
  const [csvFile,setCsvFile] = useState<File|null>(null); const [csvReport,setCsvReport] = useState<CsvImportReport|null>(null)
  const reload = useCallback(async (signal?:AbortSignal) => { setLoading(true); try { const [record,page] = await Promise.all([getMachine(machineId),listFitments(machineId,signal)]); setMachine(record); setFitments(page.items); setError('') } catch (reason) { if (!(reason instanceof DOMException && reason.name==='AbortError')) setError(message(reason,'设备详情读取失败')) } finally { if (!signal?.aborted) setLoading(false) } },[machineId])
  useEffect(() => { const controller=new AbortController(); void Promise.resolve().then(() => reload(controller.signal)); return () => controller.abort() },[reload])
  const findParts = async () => { setBusy(true); try { const page = await listParts({q:partQuery||undefined,page:1,page_size:20,sort_by:'part_no',sort_dir:'asc'}); setParts(page.items) } catch (reason) { setError(message(reason,'配件查找失败')) } finally { setBusy(false) } }
  const saveFitment = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); const data=new FormData(event.currentTarget); try { await createFitment({machine_id:machineId,part_id:String(data.get('part_id')||''),system:clean(data.get('system')),position:clean(data.get('position')),serial_from:clean(data.get('serial_from')),serial_to:clean(data.get('serial_to')),notes:clean(data.get('notes')),priority:Number(data.get('priority')||0),is_active:String(data.get('is_active'))==='true'}); setAdding(false); await reload() } catch (reason) { setError(message(reason,'适配关系保存失败')) } finally { setBusy(false) } }
  const removeFitment = async () => { if (!deleteTarget||busy) return; setBusy(true); try { await deleteFitment(deleteTarget.id); setDeleteTarget(null); await reload() } catch (reason) { setError(message(reason,'适配关系删除失败')) } finally { setBusy(false) } }
  const previewCsv = async (file?:File) => { if (!file||busy) return; setCsvFile(file); setBusy(true); setError(''); try { setCsvReport(await importFitments(machineId,file,true)) } catch (reason) { setCsvReport(null); setError(message(reason,'CSV 预检失败')) } finally { setBusy(false) } }
  const commitCsv = async () => { if (!csvFile||busy) return; setBusy(true); try { const report=await importFitments(machineId,csvFile,false); setCsvReport(report); await reload() } catch (reason) { setError(message(reason,'CSV 导入失败')) } finally { setBusy(false) } }
  return <><aside className="machine-detail-panel" aria-label="设备详情"><header><div><p>MACHINE FITMENT MATRIX</p><h2>{machine ? `${machine.brand} ${machine.model}` : '正在读取…'}</h2><span>{machine?.machine_type} · {machine?.region||'GLOBAL'}</span></div><button onClick={onClose} aria-label="关闭详情">×</button></header>{error && <p className="panel-error" role="alert">{error}</p>}{machine && <dl className="machine-nameplate"><div><dt>系列 / 年份</dt><dd>{machine.series||'—'} / {machine.year||'—'}</dd></div><div><dt>发动机</dt><dd>{machine.engine_model||'—'}</dd></div><div><dt>备注</dt><dd>{machine.notes||'—'}</dd></div><div><dt>适配记录</dt><dd>{fitments.length}</dd></div></dl>}
    <section className="fitment-section"><div className="section-title"><div><p className="eyebrow">FITMENT TAB</p><h3>适配配件</h3></div>{writable && <button className="button button--quiet" onClick={() => { setAdding(true); if (!parts.length) void findParts() }}>新增关系</button>}</div>{loading ? <div className="table-state"><i />正在读取适配关系…</div> : !fitments.length ? <p className="detail-empty">尚未关联配件，可单条添加或导入 CSV。</p> : <div className="fitment-list">{fitments.map(item => <article key={item.id}><div className="fitment-part"><strong>{item.part_no||item.part_id}</strong><span>{item.part_brand||'—'} · {item.part_name||'未命名配件'}</span></div><div><small>系统 / 位置</small><b>{item.system||'—'} / {item.position||'—'}</b></div><div className="serial-track"><small>序列号范围</small><b>{item.serial_from||'OPEN'} <i /> {item.serial_to||'OPEN'}</b></div><div><small>优先级 / 状态</small><b>{item.priority} · {item.is_active?'启用':'停用'}</b></div>{item.notes && <p>{item.notes}</p>}{writable && <button onClick={() => setDeleteTarget(item)}>删除</button>}</article>)}</div>}</section>
    {writable && <section className="fitment-section csv-import"><div className="section-title"><div><p className="eyebrow">PARTIAL SUCCESS</p><h3>批量导入 CSV</h3></div></div><p>UTF-8，列：part_id, system, position, serial_from, serial_to, priority, is_active, notes。先预检，确认后仅写入有效行。</p><label className="button button--quiet">{busy?'正在校验…':'选择 CSV 并预检'}<input hidden type="file" accept=".csv,text/csv" disabled={busy} onChange={event => void previewCsv(event.target.files?.[0])} /></label>{csvReport && <div className="csv-report" role="status"><strong>{csvReport.dry_run?'预检':'导入'}：{csvReport.processed} 行 / {csvReport.valid} 行有效 / {csvReport.errors.length} 行失败</strong>{csvReport.errors.length>0 && <ol>{csvReport.errors.slice(0,20).map(item => <li key={`${item.line}-${item.reason}`}>第 {item.line} 行 · {item.message}</li>)}</ol>}{csvReport.dry_run && csvReport.valid>0 && <button className="button" disabled={busy} onClick={() => void commitCsv()}>确认导入 {csvReport.valid} 行</button>}{!csvReport.dry_run && <b>已创建 {csvReport.created} 条关系</b>}</div>}</section>}</aside>
    <FormModal open={adding} title="新增适配关系" busy={busy} onClose={() => setAdding(false)} onSubmit={saveFitment}><label className="field-wide">查找配件<div className="part-lookup"><input aria-label="配件关键词" value={partQuery} onChange={event => setPartQuery(event.target.value)} placeholder="Part Number / OEM / 名称" /><button type="button" onClick={() => void findParts()}>查找</button></div></label><label className="field-wide">配件<select name="part_id" required defaultValue=""><option value="">请选择配件</option>{parts.map(item => <option value={item.id} key={item.id}>{item.part_no} · {item.brand} · {item.name_zh}</option>)}</select></label><label>配件系统<input name="system" /></label><label>位置<input name="position" /></label><label>序列号起<input name="serial_from" /></label><label>序列号止<input name="serial_to" /></label><label>优先级<input name="priority" type="number" min="0" defaultValue="0" /></label><label>状态<select name="is_active" defaultValue="true"><option value="true">启用</option><option value="false">停用</option></select></label><label className="field-wide">适配备注<textarea name="notes" rows={3} /></label>{error && <p className="form-error field-wide" role="alert">{error}</p>}</FormModal>
    <ConfirmDialog open={deleteTarget!=null} title="删除适配关系" description={`解除 ${deleteTarget?.part_no||''} 与当前设备的适配关系。`} busy={busy} onCancel={() => setDeleteTarget(null)} onConfirm={() => void removeFitment()} /></>
}
