import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { FormModal } from '../components/FormModal'
import { CrossReferencePanel } from '../components/CrossReferencePanel'
import { useAuth } from '../hooks/useAuth'
import { ApiError } from '../services/apiClient'
import { bulkParts, createAlias, createPart, deleteAlias, deletePartImage, exportParts, getPart, getPartOptions, listAliases, listParts, reviewAlias, setPrimaryImage, updateAlias, updatePart, updatePartImage, uploadPartImage } from '../services/partsApi'
import type { Alias, ImageType, Part, PartPayload, StockStatus } from '../types/parts'

const stockCopy: Record<StockStatus, string> = { in_stock: '有库存', low_stock: '低库存', out_of_stock: '无库存', discontinued: '停产' }
const blank: PartPayload = { sku: '', part_no: '', oem_no: null, alternate_no: null, brand: '', category: null, name_zh: '', name_en: null, name_vi: null, specs: {}, unit: '件', price: null, stock: 0, stock_status: 'in_stock', is_active: true, notes: null }
const toPayload = (part: Part): PartPayload => ({ ...part, price: part.price == null ? null : Number(part.price) })
const fieldError = (error: unknown) => {
  if (!(error instanceof ApiError)) return { form: error instanceof Error ? error.message : '保存失败' }
  const data = error.data as { field?: string; errors?: Array<{loc?: Array<string|number>;msg?:string}> } | undefined
  if (data?.field) return { [data.field]: error.message }
  if (data?.errors?.length) return Object.fromEntries(data.errors.map(item => [String(item.loc?.at(-1) || 'form'), item.msg || error.message]))
  return { form: error.message }
}

function PartForm({ part, categories, errors }: { part: PartPayload; categories: string[]; errors: Record<string,string> }) {
  const value = (key: keyof PartPayload) => part[key] == null ? '' : String(part[key])
  const field = (name: keyof PartPayload, label: string, required = false, type = 'text') => <label>{label}<input name={name} type={type} required={required} min={type === 'number' ? 0 : undefined} step={name === 'price' ? '.01' : undefined} defaultValue={value(name)} />{errors[name] && <small>{errors[name]}</small>}</label>
  return <>{field('sku', 'SKU', true)}{field('part_no', 'Part Number', true)}{field('oem_no', 'OEM 编号')}{field('alternate_no', '替代编号')}{field('name_zh', '中文名', true)}{field('name_en', '英文名')}{field('name_vi', '越南语名')}{field('brand', '品牌', true)}<label>分类<select name="category" defaultValue={value('category')}><option value="">未分类</option>{categories.map(item => <option key={item}>{item}</option>)}</select></label>{field('unit', '单位', true)}{field('price', '参考价格', false, 'number')}{field('stock', '库存数量', true, 'number')}<label>库存状态<select name="stock_status" defaultValue={part.stock_status}>{Object.entries(stockCopy).map(([key,label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>上下架<select name="is_active" defaultValue={String(part.is_active)}><option value="true">上架</option><option value="false">下架</option></select></label><label className="field-wide">规格参数（JSON）<textarea name="specs" rows={5} defaultValue={JSON.stringify(part.specs, null, 2)} />{errors.specs && <small>{errors.specs}</small>}</label><label className="field-wide">备注<textarea name="notes" rows={3} defaultValue={value('notes')} /></label>{errors.form && <p className="form-error field-wide" role="alert">{errors.form}</p>}</>
}

function parsePartForm(form: HTMLFormElement): PartPayload {
  const data = new FormData(form); let specs: Record<string, unknown>
  try { const value = JSON.parse(String(data.get('specs') || '{}')); if (!value || Array.isArray(value) || typeof value !== 'object') throw new Error(); specs = value }
  catch { throw new ApiError('规格参数必须是 JSON 对象', 422, 422, { field: 'specs' }) }
  const nullable = (name: string) => String(data.get(name) || '').trim() || null
  return { sku: String(data.get('sku') || '').trim(), part_no: String(data.get('part_no') || '').trim(), oem_no: nullable('oem_no'), alternate_no: nullable('alternate_no'), name_zh: String(data.get('name_zh') || '').trim(), name_en: nullable('name_en'), name_vi: nullable('name_vi'), brand: String(data.get('brand') || '').trim(), category: nullable('category'), unit: String(data.get('unit') || '').trim(), price: nullable('price') == null ? null : Number(data.get('price')), stock: Number(data.get('stock')), stock_status: String(data.get('stock_status')) as StockStatus, is_active: data.get('is_active') === 'true', specs, notes: nullable('notes') }
}

export function PartsPage() {
  const { partId } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const writable = user?.role === 'admin'; const [params, setParams] = useSearchParams()
  const [rows, setRows] = useState<Part[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [options, setOptions] = useState({ brands: [] as string[], categories: [] as string[] }); const [selected, setSelected] = useState<Set<string>>(new Set()); const [draft, setDraft] = useState(params.get('q') || '')
  const [editor, setEditor] = useState<Part | 'new' | null>(null); const [formBusy, setFormBusy] = useState(false); const [formErrors, setFormErrors] = useState<Record<string,string>>({}); const [bulkConfirm, setBulkConfirm] = useState<'activate'|'deactivate'|null>(null); const [bulkBusy, setBulkBusy] = useState(false); const [notice, setNotice] = useState('')
  const page = Math.max(1, Number(params.get('page') || 1)); const pageSize = 20; const pages = Math.max(1, Math.ceil(total / pageSize))
  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true); setError('')
    try { const data = await listParts({ q: params.get('q') || undefined, category: params.get('category') || undefined, brand: params.get('brand') || undefined, is_active: params.get('status') || undefined, page, page_size: pageSize, sort_by: params.get('sort') || 'created_at', sort_dir: params.get('dir') || 'desc' }, signal); setRows(data.items); setTotal(data.total) }
    catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(reason instanceof Error ? reason.message : '读取失败') } finally { if (!signal?.aborted) setLoading(false) }
  }, [page, params])
  useEffect(() => { const controller = new AbortController(); void Promise.resolve().then(() => load(controller.signal)); return () => controller.abort() }, [load])
  useEffect(() => { void getPartOptions().then(setOptions).catch(() => undefined) }, [])
  const patchParams = (values: Record<string,string>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key,value]) => { if (value) next.set(key,value); else next.delete(key) }); if (!('page' in values)) next.set('page','1'); setParams(next) }
  const sort = (key: string) => patchParams({ sort: key, dir: params.get('sort') === key && params.get('dir') === 'asc' ? 'desc' : 'asc' })
  const allPageSelected = rows.length > 0 && rows.every(row => selected.has(row.id)); const togglePage = () => setSelected(current => { const next = new Set(current); rows.forEach(row => { if (allPageSelected) next.delete(row.id); else next.add(row.id) }); return next })
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (formBusy || !editor) return; setFormBusy(true); setFormErrors({})
    try { const payload = parsePartForm(event.currentTarget); if (editor === 'new') await createPart(payload); else await updatePart(editor.id, payload); setEditor(null); setNotice(editor === 'new' ? '配件已创建' : '配件已更新'); await load() }
    catch (reason) { setFormErrors(fieldError(reason)) } finally { setFormBusy(false) }
  }
  const runBulk = async () => { if (!bulkConfirm || bulkBusy) return; setBulkBusy(true); try { const result = await bulkParts([...selected], bulkConfirm); setNotice(result.errors.length ? `${result.updated.length} 条成功，${result.errors.length} 条失败：${result.errors.map(item => item.id).join('、')}` : `${result.updated.length} 条已更新`); setSelected(current => { const next = new Set(current); result.updated.forEach(id => next.delete(id)); return next }); setBulkConfirm(null); await load() } finally { setBulkBusy(false) } }
  const currentPayload = editor === 'new' ? blank : editor ? toPayload(editor) : blank
  return <div className="parts-page"><header className="page-heading"><div><p className="eyebrow">CATALOG / MASTER DATA</p><h1>配件管理</h1><p>维护可检索、可采购的配件主数据与多语言线索。</p></div><span>ACCESS <b>{writable ? 'ADMIN WRITE' : 'OPERATOR READ ONLY'}</b></span></header>
    <section className="part-filter-deck"><form onSubmit={event => { event.preventDefault(); patchParams({ q: draft }) }}><label>搜索<input aria-label="搜索配件" value={draft} onChange={event => setDraft(event.target.value)} placeholder="Part Number / OEM / 名称" /></label><label>品牌<select aria-label="品牌筛选" value={params.get('brand') || ''} onChange={event => patchParams({ brand: event.target.value })}><option value="">全部品牌</option>{options.brands.map(item => <option key={item}>{item}</option>)}</select></label><label>分类<select aria-label="分类筛选" value={params.get('category') || ''} onChange={event => patchParams({ category: event.target.value })}><option value="">全部分类</option>{options.categories.map(item => <option key={item}>{item}</option>)}</select></label><label>状态<select aria-label="状态筛选" value={params.get('status') || ''} onChange={event => patchParams({ status: event.target.value })}><option value="">全部状态</option><option value="true">上架</option><option value="false">下架</option></select></label><button className="button" type="submit">查询</button></form></section>
    <section className="part-command-bar"><div><b>{total}</b><span>条主数据 · 已跨页选择 {selected.size} 条</span></div><div><button className="button button--quiet" disabled={!selected.size} onClick={() => void exportParts([...selected])}>导出所选 CSV</button>{writable && <><button className="button button--quiet" disabled={!selected.size || bulkBusy} onClick={() => setBulkConfirm('activate')}>批量上架</button><button className="button button--quiet" disabled={!selected.size || bulkBusy} onClick={() => setBulkConfirm('deactivate')}>批量下架</button><button className="button" onClick={() => { setFormErrors({}); setEditor('new') }}>新增配件</button></>}</div></section>
    {notice && <p className="operation-notice" role="status">{notice}<button onClick={() => setNotice('')} aria-label="关闭通知">×</button></p>}
    <section className="parts-deck" aria-busy={loading}>{loading ? <div className="table-state"><i />正在读取配件主数据…</div> : error ? <div className="table-state table-state--error" role="alert"><b>读取失败</b><span>{error}</span><button onClick={() => void load()}>重试</button></div> : !rows.length ? <div className="table-state"><b>没有符合条件的配件</b><span>调整筛选条件或创建第一条记录。</span></div> : <div className="table-scroll"><table><caption className="sr-only">配件列表</caption><thead><tr><th><input type="checkbox" aria-label="选择当前页" checked={allPageSelected} onChange={togglePage} /></th>{[['sku','SKU'],['part_no','Part Number'],['oem_no','OEM'],['name_zh','中文名'],['brand','品牌'],['category','分类'],['price','价格'],['stock','库存'],['is_active','状态']].map(([key,label]) => <th key={key}><button onClick={() => sort(key)}>{label}<span>{params.get('sort') === key ? params.get('dir') === 'asc' ? '↑' : '↓' : '↕'}</span></button></th>)}<th>操作</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><input type="checkbox" aria-label={`选择 ${row.sku}`} checked={selected.has(row.id)} onChange={() => setSelected(current => { const next = new Set(current); if (next.has(row.id)) next.delete(row.id); else next.add(row.id); return next })} /></td><td><code>{row.sku}</code></td><td><strong>{row.part_no}</strong></td><td>{row.oem_no || '—'}</td><td>{row.name_zh}</td><td>{row.brand}</td><td>{row.category || '未分类'}</td><td>{row.price == null ? '—' : `¥${Number(row.price).toFixed(2)}`}</td><td><span className={`stock-chip stock-chip--${row.stock_status}`}>{row.stock} {row.unit}</span></td><td><span className={`record-state ${row.is_active ? 'record-state--active' : ''}`}>{row.is_active ? '上架' : '下架'}</span></td><td><div className="row-actions"><Link to={`/parts/${row.id}?${params}`}>详情</Link>{writable && <button onClick={() => { setFormErrors({}); setEditor(row) }}>编辑</button>}</div></td></tr>)}</tbody></table></div>}
      {!loading && !error && <nav className="pagination" aria-label="配件列表分页"><button disabled={page <= 1} onClick={() => patchParams({ page: String(page - 1) })}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page >= pages} onClick={() => patchParams({ page: String(page + 1) })}>下一页</button></nav>}</section>
    <FormModal open={editor != null} title={editor === 'new' ? '新增配件' : `编辑 ${editor?.sku || ''}`} busy={formBusy} onClose={() => setEditor(null)} onSubmit={save}><PartForm key={editor === 'new' ? 'new' : editor?.id} part={currentPayload} categories={options.categories} errors={formErrors} /></FormModal>
    <ConfirmDialog open={bulkConfirm != null} title={bulkConfirm === 'activate' ? '批量上架' : '批量下架'} description={`将更新已选择的 ${selected.size} 条记录；不存在的记录会作为部分失败单独返回。`} busy={bulkBusy} onCancel={() => setBulkConfirm(null)} onConfirm={() => void runBulk()} />
    {partId && <PartDetail partId={partId} writable={writable} onClose={() => navigate(`/parts?${params}`)} onChanged={() => void load()} />}
  </div>
}

function PartDetail({ partId, writable, onClose, onChanged }: { partId: string; writable: boolean; onClose: () => void; onChanged: () => void }) {
  const [part, setPart] = useState<Part | null>(null); const [aliases, setAliases] = useState<Alias[]>([]); const [error, setError] = useState(''); const [imageType, setImageType] = useState<ImageType>('product'); const [uploading, setUploading] = useState(false); const [preview, setPreview] = useState(''); const [aliasEdit, setAliasEdit] = useState<Alias | 'new' | null>(null); const [aliasError, setAliasError] = useState(''); const [busy, setBusy] = useState(false); const [deleteTarget, setDeleteTarget] = useState<{type:'image'|'alias';id:string}|null>(null)
  const reload = useCallback(async () => { try { const [record, aliasPage] = await Promise.all([getPart(partId), listAliases(partId)]); setPart(record); setAliases(aliasPage.items); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : '详情读取失败') } }, [partId])
  useEffect(() => { void Promise.resolve().then(reload) }, [reload]); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview) }, [preview])
  const upload = async (file?: File) => { if (!file || uploading) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10*1024*1024) { setError('仅支持 10MB 内 JPG、PNG、WebP 图片'); return } setPreview(URL.createObjectURL(file)); setUploading(true); try { await uploadPartImage(partId, file, imageType, part?.images.length || 0); setPreview(''); await reload() } catch (reason) { setError(reason instanceof Error ? reason.message : '图片上传失败') } finally { setUploading(false) } }
  const saveAlias = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!aliasEdit || busy) return; setBusy(true); setAliasError(''); const data = new FormData(event.currentTarget); const body = { part_id: partId, alias: String(data.get('alias') || '').trim(), language: String(data.get('language') || '').trim(), region: String(data.get('region') || '').trim() || null, source: String(data.get('source') || '').trim() || null, status: String(data.get('status') || 'pending') as Alias['status'] }; try { if (aliasEdit === 'new') await createAlias(body); else await updateAlias(aliasEdit.id, body); setAliasEdit(null); await reload() } catch (reason) { setAliasError(reason instanceof Error ? reason.message : '别名保存失败') } finally { setBusy(false) } }
  const confirmDelete = async () => { if (!deleteTarget || busy) return; setBusy(true); try { if (deleteTarget.type === 'image') await deletePartImage(partId, deleteTarget.id); else await deleteAlias(deleteTarget.id); setDeleteTarget(null); await reload() } finally { setBusy(false) } }
  return <><aside className="part-detail-panel" aria-label="配件详情"><header><div><p>MASTER DATA PLATE</p><h2>{part?.sku || '正在读取…'}</h2><span>{part?.part_no}</span></div><button onClick={onClose} aria-label="关闭详情">×</button></header>{error && <p className="panel-error" role="alert">{error}</p>}{part && <><dl className="part-nameplate"><div><dt>中文名</dt><dd>{part.name_zh}</dd></div><div><dt>品牌</dt><dd>{part.brand}</dd></div><div><dt>库存状态</dt><dd>{stockCopy[part.stock_status]} / {part.stock} {part.unit}</dd></div><div><dt>状态</dt><dd>{part.is_active ? '上架' : '下架'}</dd></div></dl><section className="detail-section"><div className="section-title"><h3>图片资产</h3><span>{part.images.length} 张</span></div>{writable && <div className="image-controls"><select aria-label="图片类型" value={imageType} onChange={event => setImageType(event.target.value as ImageType)}><option value="product">实物图</option><option value="nameplate">铭牌图</option><option value="packaging">包装图</option></select><label className="button">{uploading ? '上传中…' : '上传图片'}<input type="file" hidden accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={event => void upload(event.target.files?.[0])} /></label></div>}{preview && <img className="pending-preview" src={preview} alt="待上传预览" />}{!part.images.length ? <p className="detail-empty">暂无图片资产。</p> : <div className="part-image-grid">{part.images.map((image,index) => <article key={image.id}><img src={image.url} alt={`${part.name_zh} ${index+1}`} /><div><span>{index === 0 ? '主图' : image.image_type}</span>{writable && <><button disabled={index === 0} onClick={async () => { await setPrimaryImage(partId,image.id); await reload(); onChanged() }}>设为主图</button><button disabled={index === 0} onClick={async () => { await updatePartImage(partId,{...image,sort_order:Math.max(0,image.sort_order-1)}); await reload() }}>前移</button><button onClick={() => setDeleteTarget({type:'image',id:image.id})}>删除</button></>}</div></article>)}</div>}</section><section className="detail-section"><div className="section-title"><h3>多语言别名</h3>{writable && <button className="button button--quiet" onClick={() => setAliasEdit('new')}>新增别名</button>}</div>{!aliases.length ? <p className="detail-empty">尚未添加别名。</p> : <div className="alias-list">{aliases.map(item => <article key={item.id}><div><strong>{item.alias}</strong><span>{item.language} · {item.region || 'GLOBAL'} · {item.source || '未注明来源'}</span></div><b className={`record-state ${item.status === 'active' ? 'record-state--active' : ''}`}>{item.status}</b>{writable && <div><button onClick={() => setAliasEdit(item)}>编辑</button>{item.status === 'pending' && <button onClick={async () => { await reviewAlias(item.id,'active'); await reload() }}>审核有效</button>}<button onClick={() => setDeleteTarget({type:'alias',id:item.id})}>删除</button></div>}</article>)}</div>}</section></>}</aside>
    {part && <CrossReferencePanel partId={partId} partNo={part.part_no} writable={writable} />}
    <FormModal open={aliasEdit != null} title={aliasEdit === 'new' ? '新增别名' : '编辑别名'} busy={busy} onClose={() => setAliasEdit(null)} onSubmit={saveAlias}><label>别名<input name="alias" required defaultValue={aliasEdit === 'new' ? '' : aliasEdit?.alias} /></label><label>语言<input name="language" required defaultValue={aliasEdit === 'new' ? 'zh' : aliasEdit?.language} /></label><label>地区<input name="region" defaultValue={aliasEdit === 'new' ? '' : aliasEdit?.region || ''} /></label><label>来源<input name="source" defaultValue={aliasEdit === 'new' ? '' : aliasEdit?.source || ''} /></label><label>状态<select name="status" defaultValue={aliasEdit === 'new' ? 'pending' : aliasEdit?.status}><option value="pending">待审核</option><option value="active">有效</option><option value="rejected">拒绝</option></select></label>{aliasError && <p className="form-error" role="alert">{aliasError}</p>}</FormModal>
    <ConfirmDialog open={deleteTarget != null} title={deleteTarget?.type === 'image' ? '删除图片' : '删除别名'} description="此操作会永久删除当前记录，且无法撤销。" busy={busy} onCancel={() => setDeleteTarget(null)} onConfirm={() => void confirmDelete()} />
  </>
}
