import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { AuthContext, type AuthContextValue } from '../contexts/AuthContext'
import * as partsApi from '../services/partsApi'
import * as logsApi from '../services/queryLogsApi'
import type { Part } from '../types/parts'
import type { QueryLogDetail } from '../types/queryLogs'
import { QueryLogsPage } from './QueryLogsPage'

vi.mock('../services/queryLogsApi');vi.mock('../services/partsApi')
const auth=(role:'admin'|'operator'):AuthContextValue=>({user:{id:`${role}-1`,username:role,role},ready:true,signIn:vi.fn(),signOut:vi.fn()})
const part:Part={id:'part-2',sku:'SKU-2',part_no:'RIGHT-2',oem_no:null,alternate_no:null,brand:'CAT',category:'filter',name_zh:'正确滤芯',name_en:null,name_vi:null,specs:{},unit:'件',price:null,stock:4,stock_status:'in_stock',is_active:true,notes:null,images:[],created_at:'2026-08-01',updated_at:'2026-08-01'}
const detail:QueryLogDetail={id:'log-1',session_id:'s',user_id:null,query_type:'image',source:'image',source_id:null,query_text:'CAT 320D filter',result_count:1,confidence:.82,match_status:'high',need_manual:true,duration_ms:47,created_at:'2026-08-05T01:00:00Z',client_ip:'[REDACTED]',request_data:{image_ids:['file-1']},raw_input:{image_ids:['file-1']},extracted_info:{part_no:'WRONG-1'},ai_result:{provider:'rules'},evidence:[{id:'ev-1',part_id:'part-1',confidence:.82,reason:'OCR close',evidence:[{type:'ocr',content:'WRONG-1'}]}],candidates:[{id:'part-1',part_no:'WRONG-1',brand:'CAT',name_zh:'错误滤芯',name_en:null,confidence:.82,reason:'OCR close'}],uploaded_files:[{id:'file-1',original_name:'nameplate.jpg',mime_type:'image/jpeg',size:1024,url:'https://assets/nameplate.jpg'}],llm_calls:[{id:'call-1',provider:'openai-compatible',api_mode:'responses',model:'configured',input_tokens:10,output_tokens:2,duration_ms:30,status:'success',error_type:null,error_message:null,created_at:'2026-08-05T01:00:00Z'}],selected_parts:[],correction:null}
const renderPage=(entry='/query-logs',role:'admin'|'operator'='admin')=>render(<AuthContext.Provider value={auth(role)}><MemoryRouter initialEntries={[entry]}><Routes><Route path="/query-logs" element={<QueryLogsPage/>}/><Route path="/query-logs/:queryLogId" element={<QueryLogsPage/>}/></Routes></MemoryRouter></AuthContext.Provider>)

describe('QueryLogsPage',()=>{
  beforeEach(()=>{vi.clearAllMocks();vi.mocked(logsApi.listQueryLogs).mockResolvedValue({items:[detail],total:21,page:1,page_size:20});vi.mocked(logsApi.getQueryLogStats).mockResolvedValue({period:'utc_today',query_count:12,exact_count:8,manual_count:3,exact_rate:2/3,manual_rate:.25});vi.mocked(logsApi.getQueryLog).mockResolvedValue(structuredClone(detail));vi.mocked(partsApi.listParts).mockResolvedValue({items:[part],total:1,page:1,page_size:20});vi.mocked(logsApi.correctQueryLog).mockResolvedValue({id:'fix-1',status:'pending_review',reason:'OCR 字符识别错误',actor:{id:'admin-1',username:'admin'},recommended_part:detail.candidates[0],correct_part:part,created_at:'2026-08-05T02:00:00Z'})})
  it('renders real stats and sends URL-backed source, status, date and keyword filters',async()=>{renderPage('/query-logs?source=image&status=high&from=2026-08-01&to=2026-08-05&q=CAT&page=2');expect(await screen.findByText('CAT 320D filter')).toBeInTheDocument();expect(screen.getByText('12')).toBeInTheDocument();expect(logsApi.listQueryLogs).toHaveBeenCalledWith(expect.objectContaining({source:'image',status:'high',q:'CAT',date_from:'2026-08-01T00:00:00Z',date_to:'2026-08-05T23:59:59Z',page:2}),expect.any(AbortSignal));fireEvent.change(screen.getByLabelText('查询来源'),{target:{value:'excel'}});await waitFor(()=>expect(logsApi.listQueryLogs).toHaveBeenLastCalledWith(expect.objectContaining({source:'excel',page:1}),expect.any(AbortSignal)))})
  it('shows the complete evidence chain but operator cannot submit corrections',async()=>{renderPage('/query-logs/log-1','operator');const panel=await screen.findByRole('complementary',{name:'查询详情'});expect(within(panel).getByText('CAT 320D filter')).toBeInTheDocument();expect(within(panel).getAllByText(/WRONG-1/).length).toBeGreaterThan(0);expect(within(panel).getByText('nameplate.jpg')).toBeInTheDocument();expect(within(panel).getByText(/仅管理员可提交修正/)).toBeInTheDocument();expect(within(panel).queryByRole('button',{name:'生成待审核知识候选'})).not.toBeInTheDocument()})
  it('lets an admin select a real part and append a correction',async()=>{renderPage('/query-logs/log-1');const panel=await screen.findByRole('complementary',{name:'查询详情'});const searchInput=within(panel).getAllByLabelText('搜索正确配件').find(node=>node.tagName==='INPUT')!;fireEvent.change(searchInput,{target:{value:'RIGHT-2'}});fireEvent.click(within(panel).getByRole('button',{name:'搜索'}));expect(await within(panel).findByText('正确滤芯')).toBeInTheDocument();fireEvent.click(within(panel).getByRole('button',{name:/RIGHT-2/}));fireEvent.change(within(panel).getByLabelText('错误推荐'),{target:{value:'part-1'}});fireEvent.change(within(panel).getByLabelText('修正理由'),{target:{value:'OCR 字符识别错误'}});fireEvent.click(within(panel).getByRole('button',{name:'生成待审核知识候选'}));await waitFor(()=>expect(logsApi.correctQueryLog).toHaveBeenCalledWith('log-1',{recommended_part_id:'part-1',correct_part_id:'part-2',reason:'OCR 字符识别错误'}))})
})
