import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { ApiError } from '../services/apiClient'
import { listParts } from '../services/partsApi'
import { correctQueryLog, getQueryLog, getQueryLogStats, listQueryLogs } from '../services/queryLogsApi'
import type { Part } from '../types/parts'
import type { QueryLog, QueryLogDetail, QueryLogStats } from '../types/queryLogs'

const sourceCopy={text:'文本查询',image:'图片识别',excel:'Excel 批量',manual:'人工提交'} as const
const statusCopy:Record<string,string>={exact:'精确匹配',high:'高置信',low:'低置信',multiple:'多候选',insufficient:'信息不足',not_found:'未找到'}
const fmt=(value:string)=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'short',timeStyle:'medium'}).format(new Date(value))
const pct=(value:number|null)=>value==null?'—':`${Math.round(value*100)}%`
const msg=(reason:unknown)=>reason instanceof Error?reason.message:'读取失败'
const json=(value:unknown)=>JSON.stringify(value??{},null,2)

export function QueryLogsPage(){
  const {queryLogId}=useParams();const navigate=useNavigate();const [params,setParams]=useSearchParams();const [rows,setRows]=useState<QueryLog[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const [stats,setStats]=useState<QueryLogStats>({period:'utc_today',query_count:0,exact_count:0,manual_count:0,exact_rate:0,manual_rate:0});const page=Math.max(1,Number(params.get('page')||1));const pageSize=20;const pages=Math.max(1,Math.ceil(total/pageSize));
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const data=await listQueryLogs({q:params.get('q')||undefined,source:params.get('source')||undefined,status:params.get('status')||undefined,date_from:params.get('from')?`${params.get('from')}T00:00:00Z`:undefined,date_to:params.get('to')?`${params.get('to')}T23:59:59Z`:undefined,page,page_size:pageSize},signal);setRows(data.items);setTotal(data.total)}catch(reason){if(!(reason instanceof DOMException&&reason.name==='AbortError'))setError(msg(reason))}finally{if(!signal?.aborted)setLoading(false)}},[page,params]);
  useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal));return()=>controller.abort()},[load]);useEffect(()=>{void getQueryLogStats().then(setStats).catch(()=>undefined)},[]);
  const patch=(values:Record<string,string>)=>{const next=new URLSearchParams(params);Object.entries(values).forEach(([key,value])=>value?next.set(key,value):next.delete(key));if(!('page'in values))next.set('page','1');setParams(next)};
  const refreshed=async()=>{await load();setStats(await getQueryLogStats())};
  return <div className="query-logs-page"><header className="page-heading"><div><p className="eyebrow">AUDIT STREAM / MATCH EVIDENCE</p><h1>查询日志与证据链</h1><p>复盘每次真实查询，从输入解析一路追踪到候选、证据与最终选择。</p></div><span>UTC <b>LIVE</b></span></header>
    <section className="query-stats" aria-label="查询统计"><article><span>01</span><p>今日查询</p><strong>{stats.query_count}</strong><small>UTC 自然日</small></article><article><span>02</span><p>精确匹配率</p><strong>{pct(stats.exact_rate)}</strong><small>{stats.exact_count} 次精确匹配</small></article><article><span>03</span><p>人工介入率</p><strong>{pct(stats.manual_rate)}</strong><small>{stats.manual_count} 次需要人工</small></article></section>
    <section className="query-filters"><form onSubmit={e=>e.preventDefault()}><label>关键词<input aria-label="日志关键词" value={params.get('q')||''} onChange={e=>patch({q:e.target.value})} placeholder="原始输入 / 配件号"/></label><label>查询来源<select aria-label="查询来源" value={params.get('source')||''} onChange={e=>patch({source:e.target.value})}><option value="">全部来源</option>{Object.entries(sourceCopy).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>匹配结果<select aria-label="匹配结果" value={params.get('status')||''} onChange={e=>patch({status:e.target.value})}><option value="">全部结果</option>{Object.entries(statusCopy).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>开始日期<input aria-label="日志开始日期" type="date" value={params.get('from')||''} onChange={e=>patch({from:e.target.value})}/></label><label>结束日期<input aria-label="日志结束日期" type="date" value={params.get('to')||''} onChange={e=>patch({to:e.target.value})}/></label></form></section>
    <section className="query-deck" aria-busy={loading}><div className="query-command"><b>{total}</b><span>条查询事件 · 点击时间戳打开完整证据</span></div>{loading?<div className="table-state"><i/>正在整理证据流…</div>:error?<div className="table-state table-state--error" role="alert"><b>日志读取失败</b><span>{error}</span><button onClick={()=>void load()}>重试</button></div>:!rows.length?<div className="table-state"><b>没有符合条件的真实日志</b><span>调整时间或来源筛选后再试。</span></div>:<div className="table-scroll"><table><caption className="sr-only">查询日志列表</caption><thead><tr><th>查询时间</th><th>类型</th><th>原始输入</th><th>匹配状态</th><th>置信度</th><th>人工介入</th><th>耗时</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link to={`/query-logs/${row.id}?${params}`}><code>{fmt(row.created_at)}</code></Link></td><td><span className={`source-chip source-chip--${row.source}`}>{sourceCopy[row.source]}</span><small>{row.query_type}</small></td><td title={row.query_text||''}>{row.query_text||'—'}</td><td><span className={`match-chip match-chip--${row.match_status||'pending'}`}>{statusCopy[row.match_status||'']||'待处理'}</span></td><td><b>{pct(row.confidence)}</b></td><td>{row.need_manual?<strong className="manual-yes">需要</strong>:'否'}</td><td>{row.duration_ms==null?'—':`${row.duration_ms} ms`}</td></tr>)}</tbody></table></div>}{!loading&&!error&&<nav className="pagination" aria-label="日志分页"><button disabled={page<=1} onClick={()=>patch({page:String(page-1)})}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page>=pages} onClick={()=>patch({page:String(page+1)})}>下一页</button></nav>}</section>
    {queryLogId&&<QueryLogPanel id={queryLogId} onClose={()=>navigate(`/query-logs?${params}`)} onChanged={refreshed}/>}</div>
}

function QueryLogPanel({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>Promise<void>}){
  const {user}=useAuth();const [item,setItem]=useState<QueryLogDetail|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [partQuery,setPartQuery]=useState('');const [parts,setParts]=useState<Part[]>([]);const [correctPart,setCorrectPart]=useState<Part|null>(null);
  const reload=useCallback(async()=>{try{setItem(await getQueryLog(id));setError('')}catch(reason){setError(msg(reason))}},[id]);useEffect(()=>{void Promise.resolve().then(reload)},[reload]);
  const search=async()=>{if(!partQuery.trim())return;setBusy(true);try{setParts((await listParts({q:partQuery.trim(),is_active:'true',page:1,page_size:20,sort_by:'part_no',sort_dir:'asc'})).items)}catch(reason){setError(msg(reason))}finally{setBusy(false)}};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!item||!correctPart||busy)return;const data=new FormData(e.currentTarget);setBusy(true);setError('');try{await correctQueryLog(item.id,{recommended_part_id:String(data.get('recommended_part_id')||'')||null,correct_part_id:correctPart.id,reason:String(data.get('reason')||'')});await reload();await onChanged()}catch(reason){setError(reason instanceof ApiError&&reason.status===409?'该日志已由其他管理员修正，请刷新查看。':msg(reason))}finally{setBusy(false)}};
  if(!item)return <aside className="query-detail" aria-label="查询详情"><header><div><p>QUERY DOSSIER</p><h2>正在读取…</h2></div><button aria-label="关闭详情" onClick={onClose}>×</button></header>{error&&<p className="panel-error">{error}</p>}</aside>;
  return <aside className="query-detail" aria-label="查询详情"><header><div><p>QUERY DOSSIER / {sourceCopy[item.source]}</p><h2>{item.query_type} · {fmt(item.created_at)}</h2><span>{item.id} · {item.duration_ms??'—'} ms</span></div><button aria-label="关闭详情" onClick={onClose}>×</button></header>{error&&<p className="panel-error" role="alert">{error}</p>}
    <section className="query-input"><span>01 / ORIGINAL INPUT</span><h3>原始查询</h3><p>{item.query_text||'无文本输入'}</p>{item.uploaded_files.length>0&&<div className="query-files">{item.uploaded_files.map(file=><a href={file.url} key={file.id} target="_blank" rel="noreferrer"><b>{file.mime_type.includes('sheet')?'XLS':'FILE'}</b><span>{file.original_name}<small>{Math.ceil(file.size/1024)} KB</small></span></a>)}</div>}</section>
    <section className="query-stage-grid"><article><span>02 / REQUEST</span><h3>规则输入</h3><pre>{json(item.request_data)}</pre></article><article><span>03 / EXTRACT</span><h3>AI / OCR 解析</h3><pre>{json(item.extracted_info)}</pre></article><article><span>04 / RESULT</span><h3>匹配结果</h3><pre>{json(item.ai_result)}</pre></article></section>
    <section className="evidence-section"><div className="section-title"><div><p className="eyebrow">05 / CANDIDATE RAIL</p><h3>候选配件与证据</h3></div><span>{item.candidates.length} CANDIDATES</span></div>{!item.candidates.length?<p className="detail-empty">本次查询没有候选证据。</p>:<ol className="evidence-rail">{item.candidates.map((part,index)=><li key={part.id}><i/><div><header><b>{String(index+1).padStart(2,'0')}</b><code>{part.part_no}</code><strong>{pct(part.confidence??null)}</strong></header><span>{part.brand} · {part.name_zh}</span><p>{part.reason||'未记录推荐理由'}</p>{item.evidence.filter(row=>row.part_id===part.id).map(row=><pre key={row.id}>{json(row.evidence)}</pre>)}</div></li>)}</ol>}</section>
    <section className="query-stage-grid query-runtime"><article><span>06 / PROVIDER</span><h3>AI 调用</h3>{item.llm_calls.length?item.llm_calls.map(call=><div className="runtime-row" key={call.id}><b>{call.provider} / {call.model||'未记录模型'}</b><small>{call.status} · {call.duration_ms} ms · {call.input_tokens??0}+{call.output_tokens??0} tokens</small></div>):<p className="detail-empty">本次未调用 AI 服务。</p>}</article><article><span>07 / FINAL</span><h3>最终选择</h3>{item.selected_parts.length?item.selected_parts.map(part=><div className="runtime-row" key={part.id}><b>{part.part_no} · {part.name_zh}</b><small>{part.source} · 数量 {part.quantity??1}</small></div>):<p className="detail-empty">用户尚未选择配件。</p>}</article></section>
    <section className="correction-section"><div className="section-title"><div><p className="eyebrow">08 / HUMAN CORRECTION</p><h3>人工修正审计</h3></div><span>APPEND ONLY</span></div>{item.correction?<div className="correction-record"><b>待审核知识候选</b><p>{item.correction.reason}</p><span>{item.correction.recommended_part?.part_no||'原推荐未指定'} → <strong>{item.correction.correct_part?.part_no}</strong></span><small>{item.correction.actor?.username||'已离职账号'} · {fmt(item.correction.created_at)}</small></div>:user?.role!=='admin'?<p className="detail-empty">仅管理员可提交修正；你仍可查看全部日志证据。</p>:<form onSubmit={submit} className="correction-form"><label>错误推荐<select name="recommended_part_id" aria-label="错误推荐"><option value="">未指定具体候选</option>{item.candidates.map(part=><option value={part.id} key={part.id}>{part.part_no} · {part.name_zh}</option>)}</select></label><div aria-label="搜索正确配件" className="part-search"><input aria-label="搜索正确配件" value={partQuery} onChange={e=>setPartQuery(e.target.value)} placeholder="配件号 / 名称"/><button type="button" disabled={busy} onClick={()=>void search()}>搜索</button></div>{parts.length>0&&<div className="search-results">{parts.map(part=><button type="button" key={part.id} onClick={()=>setCorrectPart(part)} className={correctPart?.id===part.id?'is-selected':''}><code>{part.part_no}</code><span>{part.name_zh}</span><small>{part.brand}</small></button>)}</div>}<label>正确配件<input aria-label="正确配件" readOnly required value={correctPart?`${correctPart.part_no} · ${correctPart.name_zh}`:''}/></label><label>修正理由<textarea aria-label="修正理由" name="reason" minLength={3} maxLength={2000} required placeholder="说明原推荐错误的证据与正确判断"/></label><button className="button" disabled={busy||!correctPart}>{busy?'正在提交…':'生成待审核知识候选'}</button></form>}</section>
  </aside>
}
