import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { FormModal } from '../components/FormModal'
import { useAuth } from '../hooks/useAuth'
import { ApiError } from '../services/apiClient'
import { addTicketNote, assignTicket, getTicket, getTicketOptions, getTicketStats, listTickets, resolveTicket, searchTicketParts, updateTicketStatus } from '../services/ticketsApi'
import type { Part } from '../types/parts'
import type { ResolutionPayload, Ticket, TicketOptions, TicketStats, TicketStatus } from '../types/tickets'

const statusCopy: Record<TicketStatus,string> = { pending:'待接单', processing:'处理中', need_info:'待补充', matched:'已匹配', in_cart:'已加购', closed:'已关闭' }
const eventCopy: Record<string,string> = { created:'创建工单', assigned:'分派并接单', status_changed:'状态变更', supplemented:'用户补充资料', resolved:'确认最终配件', internal_note:'内部备注' }
const formatDate = (value: string) => new Intl.DateTimeFormat('zh-CN',{ dateStyle:'short', timeStyle:'short' }).format(new Date(value))
const formatDuration = (seconds: number) => seconds < 60 ? `${seconds} 秒` : seconds < 3600 ? `${Math.round(seconds/60)} 分钟` : `${(seconds/3600).toFixed(1)} 小时`
const message = (reason: unknown) => reason instanceof Error ? reason.message : '操作失败'

export function TicketsPage() {
  const { ticketId } = useParams(); const navigate = useNavigate(); const [params,setParams] = useSearchParams()
  const [rows,setRows] = useState<Ticket[]>([]); const [total,setTotal] = useState(0); const [loading,setLoading] = useState(true); const [error,setError] = useState('')
  const [stats,setStats] = useState<TicketStats>({pending_count:0,today_new:0,average_handling_seconds:0}); const [options,setOptions] = useState<TicketOptions>({assignees:[],brands:[]})
  const page = Math.max(1,Number(params.get('page') || 1)); const pageSize = 20; const pages = Math.max(1,Math.ceil(total/pageSize))
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(''); try { const data = await listTickets({ status:params.get('status')||undefined, assignee_id:params.get('assignee')||undefined, date_from:params.get('from') ? `${params.get('from')}T00:00:00Z` : undefined, date_to:params.get('to') ? `${params.get('to')}T23:59:59Z` : undefined, machine_brand:params.get('brand')||undefined, page, page_size:pageSize, sort:params.get('sort')||'priority', order:params.get('order')||'asc' },signal); setRows(data.items); setTotal(data.total) } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(message(reason)) } finally { if (!signal?.aborted) setLoading(false) } },[page,params])
  const refreshAll = useCallback(async () => { await load(); setStats(await getTicketStats()) },[load])
  useEffect(() => { const controller = new AbortController(); void Promise.resolve().then(() => load(controller.signal)); return () => controller.abort() },[load])
  useEffect(() => { void Promise.all([getTicketStats(),getTicketOptions()]).then(([summary,lookups]) => { setStats(summary); setOptions(lookups) }).catch(() => undefined) },[])
  const patchParams = (values:Record<string,string>) => { const next = new URLSearchParams(params); Object.entries(values).forEach(([key,value]) => value ? next.set(key,value) : next.delete(key)); if (!('page' in values)) next.set('page','1'); setParams(next) }
  return <div className="tickets-page"><header className="page-heading"><div><p className="eyebrow">RESPONSE DESK / MANUAL MATCH</p><h1>人工工单响应台</h1><p>集中调度疑难配件查询，并把人工结论沉淀为待审核知识。</p></div><span>QUEUE <b>LIVE</b></span></header>
    <section className="ticket-stats" aria-label="工单统计"><article><span>01</span><p>待处理</p><strong>{stats.pending_count}</strong><small>尚未接单</small></article><article><span>02</span><p>今日新增</p><strong>{stats.today_new}</strong><small>UTC 自然日</small></article><article><span>03</span><p>平均处理时长</p><strong>{formatDuration(stats.average_handling_seconds)}</strong><small>已匹配及已关闭工单</small></article></section>
    <section className="ticket-filter-deck"><label>状态<select aria-label="状态筛选" value={params.get('status')||''} onChange={e=>patchParams({status:e.target.value})}><option value="">全部状态</option>{Object.entries(statusCopy).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>处理人<select aria-label="处理人筛选" value={params.get('assignee')||''} onChange={e=>patchParams({assignee:e.target.value})}><option value="">全部处理人</option>{options.assignees.map(item=><option value={item.id} key={item.id}>{item.username}</option>)}</select></label><label>开始日期<input aria-label="开始日期" type="date" value={params.get('from')||''} onChange={e=>patchParams({from:e.target.value})}/></label><label>结束日期<input aria-label="结束日期" type="date" value={params.get('to')||''} onChange={e=>patchParams({to:e.target.value})}/></label><label>设备品牌<select aria-label="设备品牌筛选" value={params.get('brand')||''} onChange={e=>patchParams({brand:e.target.value})}><option value="">全部品牌</option>{options.brands.map(item=><option key={item}>{item}</option>)}</select></label><label>排序<select aria-label="工单排序" value={params.get('sort')||'priority'} onChange={e=>patchParams({sort:e.target.value,order:e.target.value==='priority'?'asc':'desc'})}><option value="priority">待处理优先</option><option value="updated_at">最近更新</option><option value="created_at">最近创建</option></select></label></section>
    <section className="ticket-deck" aria-busy={loading}><div className="ticket-command"><b>{total}</b><span>张工单 · 工单号进入处理面板</span></div>{loading?<div className="table-state"><i/>正在同步工单队列…</div>:error?<div className="table-state table-state--error" role="alert"><b>工单读取失败</b><span>{error}</span><button onClick={()=>void load()}>重试</button></div>:!rows.length?<div className="table-state"><b>当前筛选下没有工单</b><span>积压清零，或调整筛选范围。</span></div>:<div className="table-scroll"><table><caption className="sr-only">人工工单列表</caption><thead><tr><th>工单号</th><th>用户</th><th>设备型号</th><th>配件描述</th><th>状态</th><th>处理人</th><th>创建时间</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link to={`/tickets/${row.id}?${params}`}><code>{row.ticket_no}</code></Link></td><td><strong>{row.contact_name}</strong><small>{row.country||'地区未填'}</small></td><td>{[row.machine_brand,row.machine_model].filter(Boolean).join(' ')||'—'}</td><td title={row.part_description}>{row.part_description}</td><td><span className={`ticket-status ticket-status--${row.status}`}>{statusCopy[row.status]}</span></td><td>{row.assignee_name||'未分配'}</td><td>{formatDate(row.created_at)}</td></tr>)}</tbody></table></div>} {!loading&&!error&&<nav className="pagination" aria-label="工单分页"><button disabled={page<=1} onClick={()=>patchParams({page:String(page-1)})}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page>=pages} onClick={()=>patchParams({page:String(page+1)})}>下一页</button></nav>}</section>
    {ticketId&&<TicketDetail ticketId={ticketId} onClose={()=>navigate(`/tickets?${params}`)} onChanged={refreshAll}/>}</div>
}

type Action = 'need_info'|'close'|'note'|null
interface SelectedPart { part:Part; quantity:number; confidence:number; reason:string }
function TicketDetail({ticketId,onClose,onChanged}:{ticketId:string;onClose:()=>void;onChanged:()=>Promise<void>}) {
  const {user}=useAuth(); const [ticket,setTicket]=useState<Ticket|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [action,setAction]=useState<Action>(null)
  const [partQuery,setPartQuery]=useState(''); const [results,setResults]=useState<Part[]>([]); const [searching,setSearching]=useState(false); const [selected,setSelected]=useState<SelectedPart[]>([])
  const reload=useCallback(async()=>{ try { setTicket(await getTicket(ticketId)); setError('') } catch(reason){setError(message(reason))}},[ticketId])
  useEffect(()=>{void Promise.resolve().then(reload)},[reload])
  const run=async(task:()=>Promise<Ticket>)=>{if(busy)return;setBusy(true);setError('');try{setTicket(await task());await onChanged()}catch(reason){setError(reason instanceof ApiError&&reason.status===409?`状态冲突：${reason.message}。请刷新后按当前状态操作。`:message(reason))}finally{setBusy(false)}}
  const submitAction=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!ticket||!action)return;const data=new FormData(event.currentTarget);const content=String(data.get('content')||'').trim();const current=action;await run(()=>current==='need_info'?updateTicketStatus(ticket.id,'need_info',content):current==='close'?updateTicketStatus(ticket.id,'closed',content):addTicketNote(ticket.id,content));setAction(null)}
  const search=async(event:FormEvent)=>{event.preventDefault();if(!partQuery.trim())return;setSearching(true);try{setResults((await searchTicketParts(partQuery.trim())).items)}catch(reason){setError(message(reason))}finally{setSearching(false)}}
  const resolve=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!ticket||!selected.length)return;const data=new FormData(event.currentTarget);const payload:ResolutionPayload={resolved_part_ids:selected.map(item=>item.part.id),match_evidence:String(data.get('evidence')||'').trim(),internal_note:String(data.get('internal_note')||'').trim(),quantities:Object.fromEntries(selected.map(item=>[item.part.id,item.quantity])),confidences:Object.fromEntries(selected.map(item=>[item.part.id,item.confidence])),reasons:Object.fromEntries(selected.map(item=>[item.part.id,item.reason]))};await run(()=>resolveTicket(ticket.id,payload))}
  const addPart=(part:Part)=>setSelected(current=>current.some(item=>item.part.id===part.id)?current:[...current,{part,quantity:ticket?.quantity||1,confidence:1,reason:''}])
  const updatePart=(id:string,values:Partial<SelectedPart>)=>setSelected(current=>current.map(item=>item.part.id===id?{...item,...values}:item))
  if(!ticket)return <aside className="ticket-detail-panel"><header><div><p>TICKET DOSSIER</p><h2>正在读取…</h2></div><button onClick={onClose} aria-label="关闭详情">×</button></header>{error&&<p className="panel-error">{error}</p>}</aside>
  const canResolve=['processing','need_info'].includes(ticket.status); const canClose=['matched','in_cart'].includes(ticket.status)
  return <><aside className="ticket-detail-panel" aria-label="工单详情"><header><div><p>TICKET DOSSIER / {statusCopy[ticket.status]}</p><h2>{ticket.ticket_no}</h2><span>{formatDate(ticket.created_at)} 建立</span></div><button onClick={onClose} aria-label="关闭详情">×</button></header>{error&&<p className="panel-error" role="alert">{error}</p>}
    <section className="ticket-action-rail"><button className="button" disabled={busy||ticket.status!=='pending'||!user} title={ticket.status!=='pending'?'仅待接单状态可接单':''} onClick={()=>void run(()=>assignTicket(ticket.id,user!.id))}>接单</button><button className="button button--quiet" disabled={busy||ticket.status!=='processing'} title={ticket.status!=='processing'?'仅处理中可请求补充':''} onClick={()=>setAction('need_info')}>需补充信息</button><button className="button button--quiet" disabled={busy} onClick={()=>setAction('note')}>内部备注</button><button className="button button--danger" disabled={busy||!canClose} title={!canClose?'仅已匹配或已加购可关闭':''} onClick={()=>setAction('close')}>关闭工单</button></section>
    <dl className="ticket-contact"><div><dt>客户</dt><dd>{ticket.contact_name}</dd></div><div><dt>完整联系方式</dt><dd>{ticket.contact_info}</dd></div><div><dt>沟通工具</dt><dd>{ticket.communication_tool||'—'}</dd></div><div><dt>国家/地区</dt><dd>{ticket.country||'—'}</dd></div></dl>
    <section className="detail-section"><div className="section-title"><h3>设备与需求</h3><span>MACHINE / REQUEST</span></div><dl className="ticket-spec"><div><dt>设备</dt><dd>{[ticket.machine_type,ticket.machine_brand,ticket.machine_model].filter(Boolean).join(' / ')||'—'}</dd></div><div><dt>序列号</dt><dd>{ticket.serial_no||'—'}</dd></div><div><dt>发动机</dt><dd>{ticket.engine_model||'—'}</dd></div><div><dt>数量</dt><dd>{ticket.quantity}</dd></div></dl><p className="ticket-description">{ticket.part_description}</p>{ticket.note&&<p className="ticket-note">客户备注：{ticket.note}</p>}</section>
    <section className="detail-section"><div className="section-title"><h3>附件与 AI 初判</h3><span>{ticket.attachments.length+(ticket.excel_attachment?1:0)} FILES</span></div><div className="ticket-attachments">{ticket.attachments.map(file=><a key={file.image_id} href={file.url} target="_blank" rel="noreferrer"><img src={file.url} alt={file.original_name}/><span>{file.original_name}</span></a>)}{ticket.excel_attachment&&<a className="excel-file" href={ticket.excel_attachment.url} download><b>XLS</b><span>{ticket.excel_attachment.original_name}<small>{ticket.excel_attachment.total_rows} 行 · {ticket.excel_attachment.status}</small></span></a>}{!ticket.attachments.length&&!ticket.excel_attachment&&<p className="detail-empty">没有附件。</p>}</div><pre className="ai-result">{Object.keys(ticket.ai_preliminary_result).length?JSON.stringify(ticket.ai_preliminary_result,null,2):'暂无 AI 初判'}</pre></section>
    <section className="detail-section"><div className="section-title"><h3>最终配件</h3><span>{ticket.resolved_parts.length} ITEMS</span></div>{ticket.resolved_parts.map(item=><article className="resolved-item" key={item.part_id}><div><code>{item.part_no}</code><strong>{item.brand} · {item.name}</strong></div><b>× {item.quantity}</b><span>{item.confidence==null?'未填置信度':`${Math.round(item.confidence*100)}%`} · {item.reason||'无单项说明'}</span></article>)}{!ticket.resolved_parts.length&&<p className="detail-empty">尚未确认最终配件。</p>}</section>
    {canResolve&&<section className="detail-section resolution-workbench"><div className="section-title"><h3>回填确认配件</h3><span>KNOWLEDGE CANDIDATE</span></div><form className="part-search" onSubmit={search}><input aria-label="搜索最终配件" value={partQuery} onChange={e=>setPartQuery(e.target.value)} placeholder="Part Number / OEM / 名称"/><button disabled={searching}>{searching?'搜索中':'搜索'}</button></form>{results.length>0&&<div className="search-results">{results.map(part=><button key={part.id} type="button" disabled={selected.some(item=>item.part.id===part.id)} onClick={()=>addPart(part)}><code>{part.part_no}</code><span>{part.brand} · {part.name_zh}</span><b>＋</b></button>)}</div>}<form className="resolution-form" onSubmit={resolve}>{selected.map(item=><article key={item.part.id}><header><div><code>{item.part.part_no}</code><strong>{item.part.name_zh}</strong></div><button type="button" onClick={()=>setSelected(current=>current.filter(value=>value.part.id!==item.part.id))}>移除</button></header><label>数量<input aria-label={`${item.part.part_no} 数量`} type="number" min="1" max="100000" value={item.quantity} onChange={e=>updatePart(item.part.id,{quantity:Number(e.target.value)})}/></label><label>置信度<input aria-label={`${item.part.part_no} 置信度`} type="number" min="0" max="1" step=".01" value={item.confidence} onChange={e=>updatePart(item.part.id,{confidence:Number(e.target.value)})}/></label><label className="wide">单项说明<input aria-label={`${item.part.part_no} 说明`} value={item.reason} onChange={e=>updatePart(item.part.id,{reason:e.target.value})}/></label></article>)}<label>匹配依据<textarea name="evidence" required rows={3}/></label><label>内部备注<textarea name="internal_note" rows={2}/></label><button className="button" disabled={busy||!selected.length}>{busy?'正在提交…':'确认匹配并生成待审核知识'}</button></form></section>}
    <section className="detail-section"><div className="section-title"><h3>处理时间线</h3><span>{ticket.timeline.length} EVENTS</span></div><ol className="ticket-timeline">{ticket.timeline.map(event=><li key={event.id}><i/><div><strong>{eventCopy[event.event_type]||event.event_type}</strong><span>{event.actor_name||'客户 / 系统'} · {formatDate(event.created_at)}</span>{event.status_to&&<small>{event.status_from?`${statusCopy[event.status_from]} → `:''}{statusCopy[event.status_to]}</small>}{event.content&&<p>{event.content}</p>}</div></li>)}</ol></section>
  </aside><FormModal open={action!=null} title={action==='need_info'?'填写需补充项':action==='close'?'填写关闭原因':'新增内部备注'} busy={busy} onClose={()=>setAction(null)} onSubmit={submitAction}><label className="field-wide">{action==='close'?'关闭原因':action==='need_info'?'需补充内容':'备注内容'}<textarea name="content" required rows={5}/></label></FormModal></>
}
