import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { AuthContext, type AuthContextValue } from '../contexts/AuthContext'
import { ApiError } from '../services/apiClient'
import * as ticketsApi from '../services/ticketsApi'
import type { Part } from '../types/parts'
import type { Ticket } from '../types/tickets'
import { TicketsPage } from './TicketsPage'

vi.mock('../services/ticketsApi')
beforeAll(() => { HTMLDialogElement.prototype.showModal = function(){this.setAttribute('open','')}; HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')} })
const auth:AuthContextValue={user:{id:'op-1',username:'operator',role:'operator'},ready:true,signIn:vi.fn(),signOut:vi.fn()}
const ticket:Ticket={id:'ticket-1',ticket_no:'MT-20260805-ABC',status:'pending',contact_name:'Buyer',contact_info:'13812341234',country:'CN',communication_tool:'wechat',machine_type:'forklift',machine_brand:'Toyota',machine_model:'8FD',serial_no:'SN-9',engine_model:'1DZ',part_description:'液压滤芯总成',quantity:2,note:'加急',ai_preliminary_result:{candidate:'P1'},excel_batch_id:null,excel_attachment:null,assignee_id:null,assignee_name:null,match_evidence:null,internal_note:null,attachments:[{image_id:'img-1',url:'https://assets.test/nameplate.jpg',original_name:'nameplate.jpg',mime_type:'image/jpeg',size:12}],resolved_parts:[],timeline:[{id:'event-1',event_type:'created',actor_id:null,actor_name:null,status_from:null,status_to:'pending',content:null,created_at:'2026-08-05T01:00:00Z'}],created_at:'2026-08-05T01:00:00Z',updated_at:'2026-08-05T01:00:00Z'}
const part:Part={id:'part-1',sku:'SKU-1',part_no:'PN-1',oem_no:'OEM-1',alternate_no:null,brand:'CAT',category:'filter',name_zh:'液压滤芯',name_en:null,name_vi:null,specs:{},unit:'件',price:null,stock:8,stock_status:'in_stock',is_active:true,notes:null,images:[],created_at:'2026-01-01',updated_at:'2026-01-01'}
const renderPage=(entry='/tickets')=>render(<AuthContext.Provider value={auth}><MemoryRouter initialEntries={[entry]}><Routes><Route path="/tickets" element={<TicketsPage/>}/><Route path="/tickets/:ticketId" element={<TicketsPage/>}/></Routes></MemoryRouter></AuthContext.Provider>)

describe('TicketsPage',()=>{
  beforeEach(()=>{vi.clearAllMocks();vi.mocked(ticketsApi.listTickets).mockResolvedValue({items:[structuredClone(ticket)],total:21,page:1,page_size:20});vi.mocked(ticketsApi.getTicketStats).mockResolvedValue({pending_count:4,today_new:2,average_handling_seconds:5400});vi.mocked(ticketsApi.getTicketOptions).mockResolvedValue({assignees:[{id:'op-1',username:'operator',role:'operator'}],brands:['Toyota']});vi.mocked(ticketsApi.getTicket).mockResolvedValue(structuredClone(ticket));vi.mocked(ticketsApi.assignTicket).mockResolvedValue({...ticket,status:'processing',assignee_id:'op-1',assignee_name:'operator'});vi.mocked(ticketsApi.updateTicketStatus).mockResolvedValue({...ticket,status:'need_info'});vi.mocked(ticketsApi.addTicketNote).mockResolvedValue(structuredClone(ticket));vi.mocked(ticketsApi.searchTicketParts).mockResolvedValue({items:[part],total:1,page:1,page_size:12});vi.mocked(ticketsApi.resolveTicket).mockResolvedValue({...ticket,status:'matched'})})
  it('shows MVP stats and sends URL-backed filters with pending priority',async()=>{renderPage();expect(await screen.findByText('MT-20260805-ABC')).toBeInTheDocument();expect(screen.getByText('4')).toBeInTheDocument();expect(screen.getByText('1.5 小时')).toBeInTheDocument();expect(ticketsApi.listTickets).toHaveBeenCalledWith(expect.objectContaining({sort:'priority',order:'asc'}),expect.any(AbortSignal));fireEvent.change(screen.getByLabelText('状态筛选'),{target:{value:'pending'}});await waitFor(()=>expect(ticketsApi.listTickets).toHaveBeenLastCalledWith(expect.objectContaining({status:'pending'}),expect.any(AbortSignal)))})
  it('exposes complete contact, equipment, AI, attachment and timeline detail to operators',async()=>{renderPage('/tickets/ticket-1');const panel=await screen.findByRole('complementary',{name:'工单详情'});expect(within(panel).getByText('13812341234')).toBeInTheDocument();expect(within(panel).getByText('forklift / Toyota / 8FD')).toBeInTheDocument();expect(within(panel).getByText(/"candidate": "P1"/)).toBeInTheDocument();expect(within(panel).getByAltText('nameplate.jpg')).toBeInTheDocument();expect(within(panel).getByText('创建工单')).toBeInTheDocument();fireEvent.click(within(panel).getByRole('button',{name:'接单'}));await waitFor(()=>expect(ticketsApi.assignTicket).toHaveBeenCalledWith('ticket-1','op-1'))})
  it('requires requested fields and forwards them in legal transitions',async()=>{vi.mocked(ticketsApi.getTicket).mockResolvedValue({...ticket,status:'processing'});renderPage('/tickets/ticket-1');const panel=await screen.findByRole('complementary',{name:'工单详情'});fireEvent.click(within(panel).getByRole('button',{name:'需补充信息'}));const dialog=screen.getByRole('dialog',{name:'填写需补充项'});fireEvent.change(within(dialog).getByLabelText('需补充内容'),{target:{value:'请补充铭牌照片'}});fireEvent.click(within(dialog).getByRole('button',{name:'保存记录'}));await waitFor(()=>expect(ticketsApi.updateTicketStatus).toHaveBeenCalledWith('ticket-1','need_info','请补充铭牌照片'))})
  it('deduplicates selected parts, submits evidence, quantity and confidence, and surfaces 409 conflicts',async()=>{vi.mocked(ticketsApi.getTicket).mockResolvedValue({...ticket,status:'processing'});vi.mocked(ticketsApi.resolveTicket).mockRejectedValueOnce(new ApiError('already resolved',409,40936));renderPage('/tickets/ticket-1');const panel=await screen.findByRole('complementary',{name:'工单详情'});fireEvent.change(within(panel).getByLabelText('搜索最终配件'),{target:{value:'PN-1'}});fireEvent.submit(within(panel).getByLabelText('搜索最终配件').closest('form')!);await screen.findByText('CAT · 液压滤芯');fireEvent.click(screen.getByRole('button',{name:/PN-1/}));fireEvent.change(within(panel).getByLabelText('PN-1 数量'),{target:{value:'3'}});fireEvent.change(within(panel).getByLabelText('PN-1 置信度'),{target:{value:'.92'}});fireEvent.change(within(panel).getByLabelText('PN-1 说明'),{target:{value:'铭牌一致'}});fireEvent.change(within(panel).getByLabelText('匹配依据'),{target:{value:'官方目录'}});fireEvent.click(within(panel).getByRole('button',{name:'确认匹配并生成待审核知识'}));await waitFor(()=>expect(ticketsApi.resolveTicket).toHaveBeenCalledWith('ticket-1',expect.objectContaining({resolved_part_ids:['part-1'],quantities:{'part-1':3},confidences:{'part-1':.92},reasons:{'part-1':'铭牌一致'},match_evidence:'官方目录'})));expect(await screen.findByRole('alert')).toHaveTextContent('状态冲突')})
})
