"""foundation schema

Revision ID: 0e1983312174
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0e1983312174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user'))
    )
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('file_object',
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_object')),
    sa.UniqueConstraint('object_key', name=op.f('uq_file_object_object_key'))
    )
    op.create_table('machine',
    sa.Column('machine_type', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('series', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('engine_model', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine'))
    )
    op.create_index(op.f('ix_machine_brand'), 'machine', ['brand'], unique=False)
    op.create_index(op.f('ix_machine_engine_model'), 'machine', ['engine_model'], unique=False)
    op.create_index(op.f('ix_machine_machine_type'), 'machine', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machine_model'), 'machine', ['model'], unique=False)
    op.create_table('part',
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('part_no', sa.String(length=150), nullable=False),
    sa.Column('oem_no', sa.String(length=150), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('name_zh', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_vi', sa.String(length=255), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part')),
    sa.UniqueConstraint('brand', 'part_no', name=op.f('uq_part_brand'))
    )
    op.create_index(op.f('ix_part_brand'), 'part', ['brand'], unique=False)
    op.create_index(op.f('ix_part_category'), 'part', ['category'], unique=False)
    op.create_index(op.f('ix_part_is_active'), 'part', ['is_active'], unique=False)
    op.create_index(op.f('ix_part_oem_no'), 'part', ['oem_no'], unique=False)
    op.create_index(op.f('ix_part_part_no'), 'part', ['part_no'], unique=False)
    op.create_index(op.f('ix_part_sku'), 'part', ['sku'], unique=True)
    op.create_table('part_query_log',
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('query_type', sa.String(length=30), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_query_log'))
    )
    op.create_index(op.f('ix_part_query_log_created_at'), 'part_query_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_part_query_log_query_type'), 'part_query_log', ['query_type'], unique=False)
    op.create_index(op.f('ix_part_query_log_session_id'), 'part_query_log', ['session_id'], unique=False)
    op.create_table('sys_configs',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_sys_configs'))
    )
    op.create_table('ai_match_evidence',
    sa.Column('query_log_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_ai_match_evidence_part_id_part'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_log_id'], ['part_query_log.id'], name=op.f('fk_ai_match_evidence_query_log_id_part_query_log'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_match_evidence'))
    )
    op.create_index(op.f('ix_ai_match_evidence_part_id'), 'ai_match_evidence', ['part_id'], unique=False)
    op.create_index(op.f('ix_ai_match_evidence_query_log_id'), 'ai_match_evidence', ['query_log_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_cart_item_part_id_part'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_item')),
    sa.UniqueConstraint('session_id', 'part_id', name=op.f('uq_cart_item_session_id'))
    )
    op.create_index(op.f('ix_cart_item_part_id'), 'cart_item', ['part_id'], unique=False)
    op.create_index(op.f('ix_cart_item_session_id'), 'cart_item', ['session_id'], unique=False)
    op.create_table('machine_part_relation',
    sa.Column('machine_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('serial_from', sa.String(length=100), nullable=True),
    sa.Column('serial_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], name=op.f('fk_machine_part_relation_machine_id_machine'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_machine_part_relation_part_id_part'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_part_relation')),
    sa.UniqueConstraint('machine_id', 'part_id', name=op.f('uq_machine_part_relation_machine_id'))
    )
    op.create_index(op.f('ix_machine_part_relation_machine_id'), 'machine_part_relation', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_part_relation_part_id'), 'machine_part_relation', ['part_id'], unique=False)
    op.create_table('manual_ticket',
    sa.Column('ticket_no', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('extracted_info', sa.JSON(), nullable=False),
    sa.Column('result_part_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['result_part_id'], ['part.id'], name=op.f('fk_manual_ticket_result_part_id_part'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_ticket'))
    )
    op.create_index(op.f('ix_manual_ticket_session_id'), 'manual_ticket', ['session_id'], unique=False)
    op.create_index(op.f('ix_manual_ticket_status'), 'manual_ticket', ['status'], unique=False)
    op.create_index(op.f('ix_manual_ticket_ticket_no'), 'manual_ticket', ['ticket_no'], unique=True)
    op.create_table('part_alias',
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_part_alias_part_id_part'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_alias')),
    sa.UniqueConstraint('part_id', 'alias', 'language', name=op.f('uq_part_alias_part_id'))
    )
    op.create_index(op.f('ix_part_alias_alias'), 'part_alias', ['alias'], unique=False)
    op.create_index(op.f('ix_part_alias_part_id'), 'part_alias', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_alias_status'), 'part_alias', ['status'], unique=False)
    op.create_table('part_cross_reference',
    sa.Column('source_part_id', sa.String(length=36), nullable=False),
    sa.Column('target_part_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('reliability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_part_id'], ['part.id'], name=op.f('fk_part_cross_reference_source_part_id_part'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_part_id'], ['part.id'], name=op.f('fk_part_cross_reference_target_part_id_part'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_cross_reference'))
    )
    op.create_index('ix_cross_ref_pair', 'part_cross_reference', ['source_part_id', 'target_part_id'], unique=True)
    op.create_index(op.f('ix_part_cross_reference_source_part_id'), 'part_cross_reference', ['source_part_id'], unique=False)
    op.create_index(op.f('ix_part_cross_reference_target_part_id'), 'part_cross_reference', ['target_part_id'], unique=False)
    op.create_table('part_image',
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_part_image_part_id_part'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part_image'))
    )
    op.create_index(op.f('ix_part_image_file_id'), 'part_image', ['file_id'], unique=False)
    op.create_index(op.f('ix_part_image_part_id'), 'part_image', ['part_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_image_part_id'), table_name='part_image')
    op.drop_index(op.f('ix_part_image_file_id'), table_name='part_image')
    op.drop_table('part_image')
    op.drop_index(op.f('ix_part_cross_reference_target_part_id'), table_name='part_cross_reference')
    op.drop_index(op.f('ix_part_cross_reference_source_part_id'), table_name='part_cross_reference')
    op.drop_index('ix_cross_ref_pair', table_name='part_cross_reference')
    op.drop_table('part_cross_reference')
    op.drop_index(op.f('ix_part_alias_status'), table_name='part_alias')
    op.drop_index(op.f('ix_part_alias_part_id'), table_name='part_alias')
    op.drop_index(op.f('ix_part_alias_alias'), table_name='part_alias')
    op.drop_table('part_alias')
    op.drop_index(op.f('ix_manual_ticket_ticket_no'), table_name='manual_ticket')
    op.drop_index(op.f('ix_manual_ticket_status'), table_name='manual_ticket')
    op.drop_index(op.f('ix_manual_ticket_session_id'), table_name='manual_ticket')
    op.drop_table('manual_ticket')
    op.drop_index(op.f('ix_machine_part_relation_part_id'), table_name='machine_part_relation')
    op.drop_index(op.f('ix_machine_part_relation_machine_id'), table_name='machine_part_relation')
    op.drop_table('machine_part_relation')
    op.drop_index(op.f('ix_cart_item_session_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_part_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_ai_match_evidence_query_log_id'), table_name='ai_match_evidence')
    op.drop_index(op.f('ix_ai_match_evidence_part_id'), table_name='ai_match_evidence')
    op.drop_table('ai_match_evidence')
    op.drop_table('sys_configs')
    op.drop_index(op.f('ix_part_query_log_session_id'), table_name='part_query_log')
    op.drop_index(op.f('ix_part_query_log_query_type'), table_name='part_query_log')
    op.drop_index(op.f('ix_part_query_log_created_at'), table_name='part_query_log')
    op.drop_table('part_query_log')
    op.drop_index(op.f('ix_part_sku'), table_name='part')
    op.drop_index(op.f('ix_part_part_no'), table_name='part')
    op.drop_index(op.f('ix_part_oem_no'), table_name='part')
    op.drop_index(op.f('ix_part_is_active'), table_name='part')
    op.drop_index(op.f('ix_part_category'), table_name='part')
    op.drop_index(op.f('ix_part_brand'), table_name='part')
    op.drop_table('part')
    op.drop_index(op.f('ix_machine_model'), table_name='machine')
    op.drop_index(op.f('ix_machine_machine_type'), table_name='machine')
    op.drop_index(op.f('ix_machine_engine_model'), table_name='machine')
    op.drop_index(op.f('ix_machine_brand'), table_name='machine')
    op.drop_table('machine')
    op.drop_table('file_object')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
